### ISSUE TITLE
Earnings Trends DataFrame

### ISSUE THREAD

**Issue by diegorebi** [dpguthrie/yahooquery#10]
Hi, im having problems handling de Earnings Trends Dataframe
T
![image](https://user-images.githubusercontent.com/64731837/80912649-cb6cf800-8d14-11ea-9a4c-4f10b6964303.png)

Also try this:
![image](https://user-images.githubusercontent.com/64731837/80912663-f22b2e80-8d14-11ea-85b6-17cd0bdb6fb8.png)

Thank you very much!
Great Work this code

**Comment by dpguthrie** [comment]
This module isn't as straightforward as far as converting the data to a DataFrame.  You can actually create several different DataFrames from the result.  Try something like this:

```
data = aapl.earnings_trend
df = pd.DataFrame(data['aapl']['trend'])
df_columns = ['earningsEstimate', 'revenueEstimate', 'epsTrend', 'epsRevisions']
existing_columns = ['maxAge', 'period', 'endDate', 'growth']
dataframes = {k: pd.concat([pd.json_normalize(df[k]), df[existing_columns]], axis=1) for k in df_columns}
```

That will give you a dictionary of DataFrames with each element of df_columns as a key.

**Comment by diegorebi** [comment]
Thank you very much! Im gonna try this!
