### ISSUE TITLE
p_get_financial_data can get all quarterly/TTM financial reports

### ISSUE THREAD

**Issue by zhenyulin** [dpguthrie/yahooquery#101]
**Is your feature request related to a problem? Please describe.**
Currently, p_get_financial_data will return all historical annual reports (type 12M) and the latest copy of the annualised quarterly report (type TTM), would it be possible to get all the TTM reports as well ideally from a start date?

Is this currently returned directly from Yahoo or calculated in the package?

**Comment by dpguthrie** [comment]
Not something that this package is able to do.  The TTM number is coming directly from the API response.  Happy to accept a PR if you have a way to build that number over time.
