### ISSUE TITLE
Cannot be used on Chinese network

### ISSUE THREAD

**Issue by Wangwuyi123** [dpguthrie/yahooquery#105]
![image](https://user-images.githubusercontent.com/51237097/155664066-8ad39731-6a04-424e-bf39-27b572e1b977.png)

I would like to ask whether you have stopped the support in China.

**Comment by qianyun210603** [comment]
I don't think this can be fixed without using a proxy. And this time we cannot even blame GFW. If you visit https://finance.yahoo.com/ with your browser, this will be what you see:
![image](https://user-images.githubusercontent.com/18441788/160267427-b72c2da4-cd99-4731-aefd-0b690019f580.png)

**Comment by dpguthrie** [comment]
Don't think that's something that I'm able to fix from my end.  Gonna close this out as out of scope of this project, but have you tried using a proxy?
