### ISSUE TITLE
Technical Insights Give 404 error

### ISSUE THREAD

**Issue by wparker1339** [dpguthrie/yahooquery#109]
After loading the S&P 500 tickers using the Ticker class instantiation, technical insights command returns a 404 error.  Changing settings on the backoff_factor, retry, and status_forcelist do not appear to correct the issue.

**Comment by dpguthrie** [comment]
My guess is this more due to rate limiting than anything if you're trying to retrieve 500 symbols at once.  The actual property still retrieves data itself - https://www.loom.com/share/9030382ab4484e41b979cdd129e383ed
