### ISSUE TITLE
Custom screeners

### ISSUE THREAD

**Issue by mdukaczewski** [dpguthrie/yahooquery#11]
Is there possibility to get custom screener using your lib? I mean those in section "My Saved Screeners" after logging in?

**Comment by dpguthrie** [comment]
Yeah, I’ve already begun looking into incorporating that functionality. Should be available in the next version.

**Comment by dpguthrie** [comment]
Don't plan on adding this feature at this time.  Would love a PR if it's something you'd like to add.
