### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by Pzzzzz5142** [dpguthrie/yahooquery#12]
**Is your feature request related to a problem? Please describe.**

I'm writing a app which is using async framework. Though this package support getting stock price asynchronously, can it use key word `await` to get the stock price? For it still somewhat a kind of synchronous code in an asynchronous framework. 

**Describe the solution you'd like**

add function like `async def get(self)` to get the stock price.

**Describe alternatives you've considered**

**Additional context**

**Comment by dpguthrie** [comment]
I'd be more than happy to accept a pull request, but I don't have any plans to change the way requests are made at the moment.
