### ISSUE TITLE
tickers.history fails when a single ticker is unknown

### ISSUE THREAD

**Issue by jakemdrew** [dpguthrie/yahooquery#121]
**Describe the bug**
When Ticker() contains a single unknown ticker, a call to tickers.history fails.

**To Reproduce**

.from yahooquery import Ticker

ticker_list = ['ANVI']
tickers = Ticker(ticker_list, asynchronous=True, progress=True, validate=True)
hist = tickers.history(period='30d', interval='1d')

**Expected behavior**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10884\2113441814.py in <module>
      5 tickers = Ticker(ticker_list, asynchronous=True, progress=True, validate=True)
      6 
----> 7 hist = tickers.history(period='30d', interval='1d')

C:\ProgramData\Anaconda3\envs\Prod_10Q\lib\site-packages\yahooquery\ticker.py in history(self, period, interval, start, end, adj_timezone, adj_ohlc)
   1240         else:
   1241             data = self._get_data("chart", params)
-> 1242             df = self._historical_data_to_dataframe(data, params, adj_timezone)
   1243         if adj_ohlc and "adjclose" in df:
   1244             df = self._adjust_ohlc(df)

C:\ProgramData\Anaconda3\envs\Prod_10Q\lib\site-packages\yahooquery\ticker.py in _historical_data_to_dataframe(self, data, params, adj_timezone)
   1272                 d[symbol] = data[symbol]
   1273         if all(isinstance(d[key], pd.DataFrame) for key in d):
-> 1274             df = pd.concat(d, names=["symbol", "date"], sort=False)
   1275             if "dividends" in df.columns:
   1276                 df["dividends"].fillna(0, inplace=True)

C:\ProgramData\Anaconda3\envs\Prod_10Q\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

C:\ProgramData\Anaconda3\envs\Prod_10Q\lib\site-packages\pandas\core\reshape\concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    344     ValueError: Indexes have overlapping values: ['a']
    345     """
--> 346     op = _Concatenator(
    347         objs,
    348         axis=axis,

C:\ProgramData\Anaconda3\envs\Prod_10Q\lib\site-packages\pandas\core\reshape\concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    401 
    402         if len(objs) == 0:
--> 403             raise ValueError("No objects to concatenate")
    404 
    405         if keys is None:

ValueError: No objects to concatenate

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome

**Comment by dpguthrie** [comment]
Just merged in some code via #118 that solves for this (kinda).  With the new code I merged in the other day, what would happen is an empty dataframe would be returned.  But, I could also see where maybe a request shouldn't even be made as no symbols exist after going through that initial validate step.  Curious what you think here if we should just stop execution altogether and raise an error if no symbols exist (my initial take is that we should).

[Brief loom video detailing what I said above](https://www.loom.com/share/1770e7895c274603be61bb33a8f1f0e3)

**Comment by jakemdrew** [comment]
In my case, I have no way of knowing that the remaining ticker in my list
is invalid in yahoo finance. I get them from the sec cik file.

My only current solution is to shove a ticker that I know is good like AAPL
into a ticker list len() == 1 to make sure I get back some data.

I like the idea of returning an empty dataframe so they just get handled in
my joins. Catching and coding around that error is a lot of extra work
using conditional joins.

**Comment by dpguthrie** [comment]
Cool - I'll leave as is then.  I'll cut a new release here within the next few days and this behavior will be fixed (or you can just pull directly from the main branch in the meantime).  I'm gonna close this out though as fixed.
