### ISSUE TITLE
history: faulty ticker needed otherwise empty DataFrame

### ISSUE THREAD

**Issue by sanderlenselink** [dpguthrie/yahooquery#125]
**Describe the bug**
Strange situation that a faulty ticker is needed to produce a table with dates, symbols, prices (values).

A list with no faulty tickers produces an Empy DataFrame
See also "Expected behavior" 

**To Reproduce**
import pandas as pd
from yahooquery import Ticker
funds = ['aapl', 'amzn', 'nflx', 'goog']
#funds = ['fb', 'aapl', 'amzn', 'nflx', 'goog']
ticker_def = Ticker(funds, asynchronous=True)
ticker_responses = ticker_def.history(period='1mo', interval='1wk')
prices_from_response = list()
for symbol in funds:
    ticker_data = ticker_responses.get(symbol)
    if isinstance(ticker_data, pd.DataFrame):
        ticker_close = ticker_data["close"]
        for date, value in ticker_close.iteritems():
            record = {
                "symbol": symbol,
                "data": str(date),
                "value": value
            }
            prices_from_response.append(record)
output_table = pd.DataFrame(prices_from_response)
print(output_table)

**Expected behavior**
If you run the line "#funds = ['fb', 'aapl', 'amzn', 'nflx', 'goog']" the code produces the expected/wanted table

As you can imagine e.g. companies goes private or tickers change (fb becomes meta) and you often don't know that and that's why you have to have a provision.

**Screenshots**
See attachement for the wanted final table

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Versie 107.0.5304.88 (Officiële build) (64-bits)
 - Version 

107.0.5304.88 (Officiële build) (64-bits)

**Smartphone (please complete the following information):**

**Additional context**

**EXPECTED final table:**

![yahooquery](https://user-images.githubusercontent.com/12017033/200836525-bb711b4f-678b-443e-ae6b-e4567093540a.png)

**Jupyter . . . result Empty DataFrame**
If you change funds to "funds = ['fb', 'aapl', 'amzn', 'nflx', 'goog']" the gives the expected/wanted table

![yahooquery2 png](https://user-images.githubusercontent.com/12017033/200838123-35aab76d-d313-4184-a256-97036cefa33d.jpg)

**Comment by maread99** [comment]
Hi @sanderlenselink.

I think you'll find this is happening because your `ticker_responses` here will be a `dict` when there is an invalid symbol and a `DataFrame` otherwise. When it's a `DataFrame` then `ticker_data = ticker_responses.get(symbol)` is assigning `None` to `ticker_data` as no column is named as any of the symbols.

Also, note that the recently merged PR #118 has changed the behavior. Looks like in future the return from `.history` will always be a `DataFrame` and invalid symbols will be silently ignored (i.e. they just won't be included to the `DataFrame`).

**Comment by sanderlenselink** [comment]
@maread99 ... thnx for your reply. 
Your explanation sounds (for me as a non-technician) plausible. It looks indeed familiar with #118 cq #121  

yahooquery remains a fantastic tool

**Comment by dpguthrie** [comment]
This should be resolved in 2.3.0.  Gonna close this out but feel free to open if you still see this issue.
