### ISSUE TITLE
fund_profile stale data ?

### ISSUE THREAD

**Issue by sameerdhar23** [dpguthrie/yahooquery#132]
The data obtained from the following query is stale
fund = 'qqq'
funddict = Ticker(fund)
funddict_fund_profile = funddict.fund_profile
#### Running this for TOTAL ASSETS that presumably is AUM ?? ###########
totalassets = funddict_fund_profile[fund]['feesExpensesInvestment']['totalNetAssets']

###### gives 423596.22 which is $423 Bn ? ##########

Whereas actual from Yahoo Finance is : 151.48 Bn (attached picture)

Similarly I tried for many ETFs, but everywhere "totalNetAssets" data fetched is incorrect.

I wanted to check if anyone knows 
![stale](https://user-images.githubusercontent.com/119382388/204424634-e52fc8e0-908e-45fd-87b0-0b2cc4defc71.jpg)
why is the data stale ? 
Is there a bug in the API that needs to be fixed ?

**Comment by dpguthrie** [comment]
That data corresponds to the table below your screenshot:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/10198967/204438840-7e266571-c829-4d9c-88bd-05c50d576990.png">

You can find that number in `key_stats`

<img width="323" alt="image" src="https://user-images.githubusercontent.com/10198967/204438903-9be48b90-4e02-4f20-bfe8-11cea09b0362.png">
