### ISSUE TITLE
Dates before 1970 cause "OverflowError: mktime argument out of range" error

### ISSUE THREAD

**Issue by charliemb2** [dpguthrie/yahooquery#133]
**Describe the bug**
(utils.__init__.py) :
`_convert_to_timestamp()` fails when using a start date that is before 1970, at least when called by Ticker.history() when start != None and start is not an instance of datetime.datetime. 

**To Reproduce**
Call `Ticker(^GSPY).history(start="1969-03-01", end="1971-01-01", interval='1d')`

**Expected behavior**
I expect any date to be accepted.
Instead, here's what I get:

  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python310\lib\site-packages\yahooquery\utils\__init__.py", line 118, in _convert_to_timestamp
    date = int(time.mktime(time.strptime(str(date), "%Y-%m-%d")))
OverflowError: mktime argument out of range

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I am passing it a string.  I suspect that timestamps before 1970 become negative integers and this somehow blows up the code somewhere.

The offending code is...
     `date = int(time.mktime(time.strptime(str(date), "%Y-%m-%d")))`
in the function definition below.

```
def _convert_to_timestamp(date=None, start=True):
    if date is None:
        date = int((-858880800 * start) + (time.time() * (not start)))
    elif isinstance(date, datetime):
        date = int(time.mktime(date.timetuple()))
    else:
        date = int(time.mktime(time.strptime(str(date), "%Y-%m-%d")))
    return date
```

**Comment by charliemb2** [comment]
I tried forcing a conversion of the start and end strings to datetime.datetime to reach a different part of the timestamp code and I get a similar error.

With start and end converted to objects as follows...
startOb=datetime.datetime(1969, 3, 1, 0, 0)   endOb=datetime.datetime(1971, 1, 1, 0, 0)

I get this error...

File "C:\Users\Charlie\AppData\Local\Programs\Python\Python310\lib\site-packages\yahooquery\utils\__init__.py", line 116, in _convert_to_timestamp
    date = int(time.mktime(date.timetuple()))
OverflowError: mktime argument out of range

**Comment by charliemb2** [comment]
Temporarily, I have applied this fix to the module.  I don't like to touch modules but I needed this functionality.

```
def _convert_to_timestamp(date=None, start=True):
    if date is None:
        date = int((-858880800 * start) + (time.time() * (not start)))
    elif isinstance(date, datetime):
        date = int(time.mktime(date.timetuple()))
    else:
        # date = int(time.mktime(time.strptime(str(date), "%Y-%m-%d")))     # <-- orig. code

        # Below is the change I made.  Similar changes can be considered for the datetime
        # case above.  However, datetime subtractions must be of matching type WRT timezone:
        # naive or aware.
        # Pass the date as a string argument to arrive at this code for dates prior to 1970.
        dt = datetime.strptime(str(date), "%Y-%m-%d")               # cb new code 2022-12-18
        date = int((dt - datetime(1970, 1, 1)).total_seconds())
    return date
```

The file location on my system is found at:
......`\Python\Python310\lib\site-packages\yahooquery\utils\__init__.py`

**Comment by nickodell** [comment]
I'm trying to reproduce this problem. I had to change the example script a little to fix the syntax. I don't encounter this error when running this modified version:

```py
from yahooquery import Ticker
print(Ticker('GSPY').history(start="1969-03-01", end="1971-01-01", interval='1d'))
```

...although Yahoo reports that they have no data during that time period, and their website doesn't show any pre-1971 data either.

Is this a Windows specific bug? Some Googling says that Python on Windows has some trouble with mktime() and pre-1970 dates.

**Comment by dpguthrie** [comment]
This no longer happens in the new release - 2.3.0

<img width="537" alt="image" src="https://user-images.githubusercontent.com/10198967/213937168-2d3d32eb-6594-4a54-bbc7-dab8b786da74.png">
