### ISSUE TITLE
New PyPI release request

### ISSUE THREAD

**Issue by maread99** [dpguthrie/yahooquery#134]
Hi @dpguthrie

I was wondering if following your recent changes and #129 there's any chance you could cut a new release for PyPI?

Cheers
Marcus

**Comment by dpguthrie** [comment]
[2.3.0 released today](https://github.com/dpguthrie/yahooquery/actions/runs/3981252103/jobs/6824860858)!  Let me know if you run into any issues.  Thanks again for your help!

**Comment by maread99** [comment]
No worries @dpguthrie. Thanks for the library!

If you get a chance to check out [market-prices](https://github.com/maread99/market_prices) I'd love to know what you think. You might find it a useful lib to direct users to who are raising issues asking for more options to query / cache / post-process the price data.

Cheers
