### ISSUE TITLE
Interactive demo is not working anymore

### ISSUE THREAD

**Issue by micktg** [dpguthrie/yahooquery#135]
**Describe the bug**
I used the interactive demo a lot to test around but unfortunately, it does not work anymore.

**To Reproduce**
1. Go to https://yahooquery.dpguthrie.com/
2. Click on the link https://yahooquery-streamlit.herokuapp.com/
3. Heroku error message is displayed

**Expected behavior**
Demo page should be displayed

**Comment by dpguthrie** [comment]
Just moved it here - https://dpguthrie-yahooquery-streamlit-app-eydpjo.streamlit.app/

**Comment by micktg** [comment]
> Just moved it here - https://dpguthrie-yahooquery-streamlit-app-eydpjo.streamlit.app/

Can you please update the link on this homepage: https://yahooquery.dpguthrie.com/

from: Interactive Demo: https://yahooquery-streamlit.herokuapp.com/
to      Interactive Demo: https://dpguthrie-yahooquery-streamlit-app-eydpjo.streamlit.app/

My guess is, that a lot of people try to use the `herokuapp` link and just land nowhere

**Comment by dpguthrie** [comment]
Done
