### ISSUE TITLE
Country input not working, default is ignored

### ISSUE THREAD

**Issue by prangon0** [dpguthrie/yahooquery#137]
```
import yahooquery as yq
data = yq.search(company_name, first_quote=True, country="united states")

print(data)
```

Works most of the time until I inputted `AMAZON COM INC` as the company. Tried leaving as default and inputting a country but it always just gives me quotes from other countries. The first quote it returns is from Mexico, and so gives me the MX ticker and wrong exchange.
```
{'exchange': 'MEX', 'shortname': 'AMAZON COM INC', 'quoteType': 'EQUITY', 'symbol': 'AMZN.MX', 'index': 'quotes', 'score': 20188.0, 'typeDisp': 'Equity', 'longname': 'Amazon.com, Inc.', 'exchDisp': 'Mexico', 'sector': 'Consumer Cyclical', 'industry': 'Internet Retail', 'dispSecIndFlag': False, 'isYahooFinance': True
```

Tried using postman and the query url `https://query2.finance.yahoo.com/v1/finance/search?q=AMAZON COM INC` (from yahooquery code) and still it gives me a list of the same ticker from many different countries. Experienced this with the inputs `RESTAURANT BRANDS INTL INC`, `SCHWAB CHARLES CORP`  and `VANGUARD INTL EQUITY INDEX F` as well.

**Comment by dpguthrie** [comment]
I don't think this is a problem with yahooquery - the package is simply returning the results that Yahoo Finance produces.  Put that same query in the search bar in Yahoo Finance and examine the request that was made.  The first quote is exactly what you have above.

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/10198967/213935653-08d0db0f-a288-45e1-a6cf-9140036959a2.png">

Unfortunately, I don't think there's anything I'm able to do to so I'm going to close this.
