### ISSUE TITLE
TypeError: sequence item 339: expected str instance, float found

### ISSUE THREAD

**Issue by Ruin2121** [dpguthrie/yahooquery#146]
**I left an update on what I found in the comments.**

**Describe the bug**
YahooQuery raises a type error while using the validate setting when attempting to pull historical data for a massive list of tickers.

Error:
```
Traceback (most recent call last):
File "C:\Users\chous\Documents\GitHub\Portfolio_and_Analysis_Tools\dbtest.py", line 8, in <module>
    tickers = Ticker(ticker_list, asynchronous=True, progress=True, validate=True)
File "C:\Users\chous\anaconda3\lib\site-packages\yahooquery\ticker.py", line 94, in __init__
    self.validation
File "C:\Users\chous\anaconda3\lib\site-packages\yahooquery\base.py", line 1017, in validation
    data = self._chunk_symbols("validation")
File "C:\Users\chous\anaconda3\lib\site-packages\yahooquery\base.py", line 999, in _chunk_symbols
    data = self._get_data(key, params, disable=True, **kwargs)
File "C:\Users\chous\anaconda3\lib\site-packages\yahooquery\base.py", line 1082, in _get_data
    urls = self._construct_urls(config, params, **kwargs)
File "C:\Users\chous\anaconda3\lib\site-packages\yahooquery\base.py", line 1147, in _construct_urls
    params.update({"symbols": ",".join(self._symbols)})
TypeError: sequence item 339: expected str instance, float found
```
**To Reproduce**
Code used: 
(The stock_list csv has 7896 entries of stock tickers that i've found on various websites. I expect that some number of the entries are bad entries that won't result in anything)
[Stock list download](https://drive.google.com/file/d/12YSRKyXWN5CSKaX5L_f23aHauU9qZCnV/view?usp=sharing)
```
from yahooquery import Ticker
import pandas as pd

ticker_df = pd.read_csv("stock_list.csv", header=0)
ticker_list = ticker_df['Tickers'].tolist()

tickers = Ticker(ticker_list, asynchronous=True, progress=True, validate=True)

df = tickers.history()

print(df.head())
```

**Expected behavior**
I expected the validation to filter out all problem tickers. Perhaps this is an uncaught issue.

**Comment by Ruin2121** [comment]
UPDATE: It seems Ticker NAN on NYSE is causing the issue, which i'm sure is related to some programming nonsense. I'll leave the issue open in case anyone wants to fix this issue (assuming it can be fixed).

**Comment by dpguthrie** [comment]
Looks like the ticker `NAN` is being coerced to `nan`, which is a float.  Just add another step that coerces everything to a string:
```python
ticker_list = ticker_df['Tickers'].tolist()
ticker_list = [str(s) for s in ticker_list]
```
