### ISSUE TITLE
Fails with `requests_cache` session

### ISSUE THREAD

**Issue by ValueRaider** [dpguthrie/yahooquery#147]
#### Reproduce

```
import yahooquery as yq

import requests_cache
session = requests_cache.CachedSession("yq.cache")

tkr = "AMZN"
dat = yq.Ticker(tkr, session=session) 
print(dat.summary_detail)
```
> {'error': 'HTTP 404 Not Found.  Please try again'}

#### Debugging
`_YahooFinance._construct_urls()` returns `[<Response [403]>]` instead of `[<Response [200]>]`

**Comment by dpguthrie** [comment]
Not sure if this is `yahooquery` related as the same forbidden response is given when using `requests_cache` by itself.

```python
import requests_cache


url = 'https://query2.finance.yahoo.com/v10/finance/quoteSummary/amzn'
params = {
    'modules': 'summaryDetail',
    'formatted': False,
    'lang': 'en-US',
    'region': 'US',
    'corsDomain': 'finance.yahoo.com',
}
session = requests_cache.CachedSession()
session.get(url, params=params)
```

**Comment by dpguthrie** [comment]
Ohhhh...actually, I think I know what may be happening here.  I think yahoo got a bit smarter in how they deal with programmatic requests.  I think if you set the user agent in the session you pass to `Ticker` then you should be good.  (haven't tested yet)

**Comment by dpguthrie** [comment]
After you initialize the session:

```
session.headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'}
```

Any valid user agent will do here.

**Comment by ValueRaider** [comment]
Thanks @dpguthrie
