### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by EmirEgilli** [dpguthrie/yahooquery#152]
I am receiving "TypeError: 'type' object is not subscriptable" when trying to call the Ticker function as below:

`import yahooquery as yq`
`amzn = yq.Ticker['AMZN']`

![image](https://user-images.githubusercontent.com/82716676/220831976-97740f04-d8ed-40c3-b7ac-a7c9a505dbdc.png)

Made sure yahooquery and Requests are up-to-date. Issue started as of this morning (GMT+3). Any help would be appreciated.

**Comment by dpguthrie** [comment]
Use parenthesis

`amzn = yq.Ticker(‘amzn’)`

**Comment by EmirEgilli** [comment]
![image](https://user-images.githubusercontent.com/82716676/220859303-bcc371c8-86c4-4a8e-a3d7-3ba02c4cf151.png)

Did you really think i didn't try with lowercase letters, or multiple tickers for that regard? That was a rather early close on this issue.

**Comment by dpguthrie** [comment]
Sorry, should've clarified. You're using brackets when you should be using parenthesis. This is the way you pass arguments to a class.
