### ISSUE TITLE
Some modules has stopped working

### ISSUE THREAD

**Issue by RobinDeeCee** [dpguthrie/yahooquery#153]
**assetProfile, summaryProfile (and possibly other ones) has stopped working**
From this morning (I think) some of the modules stopped working. Did not have the time to check if there are more but I know for a fact there is a problem in the assetProfile and  summaryProfile

**To Reproduce**
1. Go to the demo application -> https://dpguthrie-yahooquery-streamlit-app-eydpjo.streamlit.app/
2. Choose a page -> 'Modules'
3. Select Method -> 'Multiple Modules'
4. Select modules -> assetProfile, summaryProfile

**Expected behavior**
This should give back the request data, but it is not.

**Screenshots**
![image](https://user-images.githubusercontent.com/47752583/220850085-9bf02daa-5530-4e39-92cf-d4df1cffadcd.png)

**Additional context**
XXX

### EDIT
key_stats module has the same issue (reported by @galashour)

**Comment by galashour** [comment]
Same issue with for the key_stats module.

**Comment by dpguthrie** [comment]
This is pretty weird.  This appears, at least at the moment, that it's an issue on the YF side (and maybe just for `aapl`).  Found a few things that make me think that.

1.  The profile page for AAPL isn't loading right now.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/10198967/220917352-65ca7d43-d6b6-4c20-957f-7350a215a941.png">

2. When a request is made with the corresponding modules for key_stats and summary_profile, YF isn't even returning that data to their front-end for AAPL.  But appears to for other symbols.
https://www.loom.com/share/d9904bee314a4fa4a79a11a8d943d42f

I'll keep investigating this though.  Let me know if you see this behavior for other symbols.

**Comment by galashour** [comment]
I agree that it seems to be on yahoo side, since also on their website I don't seem to see some info like (div yield or x-div-date):
https://finance.yahoo.com/quote/MSFT/?p=MSFT

but, it is not specific to 'AAPL' but rather quite widespread for quite a few symbols I checked earlier today (JPM, IBM, NVDA, MSFT, etc.).

**Comment by galashour** [comment]
Problem is now solved on yahoo's end (now the web site shows the missing values), and also the yahooquery modules seem back to normal.

**Comment by RobinDeeCee** [comment]
This issue is fix indeed, sorry that I didn't see the obvious reason. I just started working with this. So I'm still in mine exploring fase.
anyway thanks for the help
