### ISSUE TITLE
all_financial_data() does not return valuation_measures data

### ISSUE THREAD

**Issue by dimitrispapasotiriou** [dpguthrie/yahooquery#159]
I am using all_financial_data module the past three days for multiple symbols and I have noticed that it is not returning valuation_measures data. I only get balance_sheet,income_statement and cashflow data. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Version: Version 110.0.5481.178 (Official Build) (64-bit)

Thank you.

**Comment by ms82494** [comment]
Try it without the "all_" in the name. This works for me:  ```Ticker(['aapl','goog','tsla']).financial_data```
