### ISSUE TITLE
Missing key values

### ISSUE THREAD

**Issue by fsitios** [dpguthrie/yahooquery#162]
### Discussed in https://github.com/dpguthrie/yahooquery/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **fsitios** February 28, 2023</sup>
Hi, does anyone know where I can get the "Income Tax Expense",  the "Income Before Taxes" and the "Short Long Term Debt" values from yahooquery? 

Thanks!</div>

**Comment by ms82494** [comment]
Income tax accruals are in the income statement (`income_statement` module), under `TaxProvision`.

I don't know what you mean by "Short Long Term Debt". The current portion of long term debt, or the sum of short and long term debt? Either way, I think the image shows the fields you need.

![image](https://user-images.githubusercontent.com/6218876/223305293-74ecd4f9-69eb-4311-9d4e-969f5bc500bd.png)

**Comment by fsitios** [comment]
Thanks for your answer, but I am migrating from Yfinance package to YahooQuery, and in Yfinance package there are these keys:
"Income Tax Expense", "Income Before Taxes", "Short Long Term Debt".
I don't know what the equivalent keys are in YahooQuery. I can't find a similar name for these cases in any module.
I will appreciate any help with these keys to finish the migration.

Kind regards.



________________________________
De: ms82494 ***@***.***>
Enviado: lunes, 6 de marzo de 2023 23:37
Para: dpguthrie/yahooquery ***@***.***>
Cc: Fernando ***@***.***>; Author ***@***.***>
Asunto: Re: [dpguthrie/yahooquery] Missing key values (Issue #162)


Income tax accruals are in the income statement (income_statement module), under TaxProvision.

I don't know what you mean by "Short Long Term Debt". The current portion of long term debt, or the sum of short and long term debt? Either way, I think the image shows the fields you need.

[image]<https://user-images.githubusercontent.com/6218876/223305293-74ecd4f9-69eb-4311-9d4e-969f5bc500bd.png>

**Comment by dpguthrie** [comment]
You can either use older and less accurate modules that YF doesn't use on their site anymore (believe it's less accurate for non-US stocks):

```python
yq.Ticker('aapl').get_modules(['balanceSheetHistory', 'incomeStatementHistory'])
```

Or use the `income_statement` and `balance_sheet` methods that are the ones used on the YF front-end.  Some mapping to get to that:

- Income Tax Expense -> TaxProvision
- Income Before Taxes -> PreTaxIncome
- Short Long Term Debt -> Not Sure (I've seen with `aapl` that you can use OtherCurrentBorrowings, but with `msft` I've seen CurrentDebt match that number).  The benefit of these methods though is it gives you very granular level detail of the levels of debt that you can aggregate to whatever level you deem necessary.

**Comment by ValueRaider** [comment]
> older and less accurate modules

I suspect this is what `yfinance` used to do before December update, now returned via `legacy=True` argument. Can't confirm while decryption broken.

These are actually very useful sometimes particularly the Quarterlies, so can documentation be clearer that these alternatives are available? Sometimes with European stocks YF doesn't display quarterly financials and so `balance_sheet(freq="quarterly")` returns `None`, but they do exist and are returned by the older modules. Even if incomplete/inaccurate they are useful.

I will try to update post with an example symbol.

**Comment by dpguthrie** [comment]
Oh interesting, didn't realize that.  Do you have an example of a European stock that returns no financials when doing:

```python
yq.Ticker(ticker).balance_sheet(freq='q')
```

vs. data being returned through the modules

**Comment by ValueRaider** [comment]
First example I found is Aussie: E25.AX quarterly cash-flow

```
yq.Ticker("E25.AX").cash_flow(frequency="q", trailing=False)
yq.Ticker("E25.AX").get_modules(["cashflowStatementHistoryQuarterly"])
```
