### ISSUE TITLE
Valid Yahoo! symbols such as the Bovespa (Brasil) index ^BVSP fail to properly process

### ISSUE THREAD

**Issue by shipmints** [dpguthrie/yahooquery#163]
**Describe the bug**
Valid Yahoo! symbols fail to properly process. I see that @maread99 has been refining history processing code, so cc'ing him here.

```
verifying and downloading ^BVSP
Length mismatch: Expected axis has 7391 elements, new values have 7385 elements
```
```
verifying and downloading ^TA125.TA
Cannot infer dst time from 2001-09-24 00:00:00, try using the 'ambiguous' argument
```
```
verifying and downloading ['^VXEEM', '^STI']
venv/lib/python3.8/site-packages/yahooquery/ticker.py:1314: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  df = pd.concat(d, names=["symbol", "date"], sort=False)
venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py:1004: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  a.sort(axis=axis, kind=kind, order=order)
```
Yet those last two symbols, when downloaded one at a time, appear to work fine.
```
verifying and downloading ^VXEEM
verifying and downloading ^STI
```

**To Reproduce**
See code to reproduce, below.

**Expected behavior**
yq should work for all valid Yahoo! symbols.

**Desktop (please complete the following information):**
macOS (repros on other o/s also, this is not o/s specific)
Python 3.8.3
yahooquery 2.3.0
pandas 1.5.3
numpy 1.23.5
pytz 2022.7.1

**Additional context**
I sense that perhaps just US-based mainstream symbols are being tested and test cases need beefing up?

```
#!/usr/bin/env python

import datetime
import yahooquery

if __name__ == '__main__':

    ticker_list = [
        # ValueError: Length mismatch: Expected axis has 7390 elements, new values have 7384 elements
        '^BVSP',
        # pytz.exceptions.AmbiguousTimeError: Cannot infer dst time from 2001-09-24 00:00:00, try using the 'ambiguous' argument
        '^TA125.TA',
        # 2023-03-07T17:26:43.716 WARNING warnings _showwarnmsg lib/python3.8/warnings.py:109 venv/lib/python3.8/site-packages/yahooquery/ticker.py:1314: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
        [
            '^VXEEM', '^STI',
        ],
        # These work fine individually
        '^VXEEM',
        '^STI',
    ]

    for t in ticker_list:
        print(f'verifying and downloading {t}')
        yt = yahooquery.Ticker(t,
                               validate=True,
                               progress=False,
                               retry=20,
                               timeout=5,
                               backoff_factor=0.3,
                               asynchronous=True,
                               max_workers=8)
        invalids = yt.invalid_symbols
        if invalids:
            print(f'yahooquery invalid symbols {invalids}')

        try:
            df = yt.history(adj_ohlc=False,
                            adj_timezone=True,
                            period='max',
                            interval='1d',
                            start=datetime.datetime(1932, 1, 1),
                            end=datetime.datetime.today())
        except Exception as e:
            print(e)

        yt.session.close() # per https://github.com/dpguthrie/yahooquery/issues/72
```

**Comment by ValueRaider** [comment]
For Brasil I have a clue - between Yahoo & Pandas the handling of Brasil DST is broken. [See how `yfinance` handles this](https://github.com/ranaroussi/yfinance/blob/7b95f554bd6019d64caceaf1809fc5af11737776/yfinance/utils.py#L672-L682)

**Comment by shipmints** [comment]
> For Brasil I have a clue - between Yahoo & Pandas the handling of Brasil DST is broken. [See how `yfinance` handles this](https://github.com/ranaroussi/yfinance/blob/7b95f554bd6019d64caceaf1809fc5af11737776/yfinance/utils.py#L672-L682)

One would hope that by now everything at Yahoo! would be normalized to GMT, at least internally, and converted for human display at the last moment.

**Comment by ValueRaider** [comment]
They don't need to normalize, they store epochs, but to generate they have to pass datetime through timezone conversion. Then `yahooquery` repeats in reverse.

**Comment by maread99** [comment]
Hi @shipmints, thanks for raising these and for cc'ing. The bugs are indeed related to the changes I made...

### ^BVSP
The bug here has its origins in inconsistent indexing by Yahoo (or rather `yahooquery` not handling the inconsistency). As explained in more detail [here](https://github.com/dpguthrie/yahooquery/issues/127#issue-1458696693), Yahoo indexes daily data with the session open time and `yahooquery` then converts this to a date. The date is evaluated as the same date as that of the local session open if that open is before 14.00, otherwise the date is evaluated as the next day (this ensures that, for example, a 24 hour instrument with a 23:00 open is assigned a date as the following day).

The following is a sample of the indexing of '^BVSP' that's being returned by yahoo (when converted to local time):
```python
DatetimeIndex(['2021-08-10 10:00:00-03:00', '2021-08-11 10:00:00-03:00',
               '2021-08-12 19:05:00-03:00', '2021-08-13 10:00:00-03:00',
               '2021-08-16 10:00:00-03:00', '2021-08-17 10:00:00-03:00',
               '2021-08-18 10:00:00-03:00', '2021-08-19 10:00:00-03:00',
               '2021-08-20 10:00:00-03:00', '2021-08-23 10:00:00-03:00',
               ...
               '2023-02-27 10:00:00-03:00', '2023-02-28 10:00:00-03:00',
               '2023-03-01 10:00:00-03:00', '2023-03-02 10:00:00-03:00',
               '2023-03-03 10:00:00-03:00', '2023-03-06 10:00:00-03:00',
               '2023-03-07 10:00:00-03:00', '2023-03-08 10:00:00-03:00',
               '2023-03-09 10:00:00-03:00', '2023-03-10 10:00:00-03:00'],
              dtype='datetime64[ns, America/Sao_Paulo]', length=396, freq=None)
```
For whatever reason on ten days during 2021 (usually the 12th of a month) the daily data is indexed with what appears to be the day close, i.e. as 2021-08-12 above. Consequently `yahooquery` is evaluating the days for these indices as the following day, but the subsequent indices are being evaluated to the same day (13th August above). Two rows being assigned the same date is behind the error being raised.

I'll PR a fix.

### ^TA125.TA
DST ambiguities are actually not important for the purpose of what the [offending line's](https://github.com/dpguthrie/yahooquery/blob/444855ec92a55883d7e08586aaa851c1ee346081/yahooquery/utils/__init__.py#L145) there for. The `.floor` / `.ceil` methods just need to be passed `ambiguous=True`. I'll include a fix to the same PR.

### ['^VXEEM', '^STI']
I haven't been able to replicate this one. When/if you get the warning again could you please post a minimal example and state the time and date the request was made together with your local time zone. Thanks.

**Comment by maread99** [comment]
> I sense that perhaps just US-based mainstream symbols are being tested and test cases need beefing up?

Very much agree that the `.history` method would benefit from wider test coverage. I'm unfortunately not in a position to be able offer anything but I'm sure @dpguthrie would appreciate a PR from anyone out there who can.

**Comment by shipmints** [comment]
@maread99 thank you for the detailed explanation and effort. Accommodating a mix of discrete trading hours and continuous can be tricky. This is the kind of thing that Yahoo! probably should have dealt with but who knows what their incentives are to improve, these days. Yahoo! Finance might be the only property they have that people use besides Mail (and without eyeballs for ads as we're API callers).

When testing to reproduce ['^VXEEM', '^STI'], did you use pandas 1.5.3 (or later)? It still produces the same warning for me in the test case, above.

**Comment by shipmints** [comment]
Confirmed that as of commit 444855ec92a55883d7e08586aaa851c1ee346081 the warning for ['^VXEEM', '^STI'] disappeared. I will test again the wacky market hours symbols once @dpguthrie  reviews your PR.

**Comment by shipmints** [comment]
Confirmed working as of commit 841f77e32e02b3e3332c8dcd23682a8d62ad9e7d

Thanks, again, for the detailed work. Not so sure about the hardcoded reference to SAO. There must be a more systematic method to detect these kinds of conditions.

**Comment by maread99** [comment]
I believe anything more general would require knowledge of the underlying exchange open/close times, and even then you'd probably have to make assumptions as to how the data might be being inconsistently indexed. I'd argue it's preferable to hardcode fixes for any specific cases that arise. If a general pattern to inconsistencies emerges then it may be worth looking at a more general way to handle them.
