### ISSUE TITLE
Getting data older than 4 years when calling functions such as "balance_sheet"

### ISSUE THREAD

**Issue by Veran04** [dpguthrie/yahooquery#166]
**Is your feature request related to a problem? Please describe.**
Hello, I am sorry if this is a silly request as I am still pretty new to financial coding and finance in general. I noticed that there is no parameter in the function calls for things like balance_sheet or cashflow other than adjusting between annual or quarterly. 

**Describe the solution you'd like**
Would it be possible to add a parameter that allows the user to get up to 10 years of history for example in order to conduct backtesting more efficiently?

**Describe alternatives you've considered**
I considered other finance api's but I really love yahooquery and want to use it for this <3

**Additional context**

**Comment by dpguthrie** [comment]
Thanks @Kalaweksh!  Unfortunately, this is true - to get more than 4 years of historical financials data, you have to be a premium subscriber. I think they offer a free trial, so try that and see if that works.

**Comment by Veran04** [comment]
You guys are my heroes, thank you so much!
