### ISSUE TITLE
Ticker.quotes returning 'HTTP 404 Not Found'

### ISSUE THREAD

**Issue by maread99** [dpguthrie/yahooquery#178]
As of this afternoon:

```python
>>> import yahooquery as yq
>>> ticker = yq.Ticker("^DJI")
>>> ticker.quotes
'HTTP 404 Not Found'
```

The url https://query2.finance.yahoo.com/v6/finance/quote is showing the error.

Any ideas @dpguthrie?

Thanks

**Comment by dpguthrie** [comment]
No problem on my end:
![image](https://user-images.githubusercontent.com/10198967/233181441-e36eae9c-23ed-41c8-9066-d386859fa834.png)

**Comment by maread99** [comment]
Thanks @dpguthrie.

I've just got it working with a VPN server in the US, although getting 404 in Europe.

**Comment by maread99** [comment]
I'm getting this 404 everywhere now 😞

@dpguthrie, would you mind checking your side again.

**Comment by ValueRaider** [comment]
UK here, I get 404.

**Comment by dpguthrie** [comment]
Well, looks like they changed the URL (I have it has `query2.finance.yahoo.com/v6/finance/quote` and it's now `query1.finance.yahoo.com/v7/finance/quote`.
![image](https://user-images.githubusercontent.com/10198967/233209576-f71ac8d7-da7a-408f-b23c-a928a6e1410d.png)

But unfortunately, they're also requiring a valid cookie to make the request.  This is after changing the URL:
![image](https://user-images.githubusercontent.com/10198967/233209529-410b304a-ad38-4a92-a86f-f8c377a7920a.png)

**Comment by ValueRaider** [comment]
Try v10

**Comment by maread99** [comment]
As at 23/03/20 09:05 UTC this is back up (for me anyway), i.e. https://query2.finance.yahoo.com/v6/finance/quote as expected and `Ticker.quotes` is working.

**Comment by pfuller88** [comment]
It is working again for me this morning 7:36 EST.   Was getting the 404 error late yesterday.

**Comment by RudyNL** [comment]
Netherlands, tried at April 20, 18:50 CET . No problems and not error messages.

**Comment by dpguthrie** [comment]
Closing as this appeared to be a spurious issue.  Please reopen if you think otherwise.
