### ISSUE TITLE
Valuation Measure for past years

### ISSUE THREAD

**Issue by charlie-delta-003** [dpguthrie/yahooquery#188]
Currently valuation measure limited only for past quarters, could you provide option for past years please? Thanks

**Comment by dpguthrie** [comment]
This is simply a limitation of Yahoo Finance.  It looks like they offer that kind of data for premium customers though.

![image](https://user-images.githubusercontent.com/10198967/235758384-b7eaa8c5-1261-498d-ac76-35eb98664be0.png)
