### ISSUE TITLE
Unable to get data for Indian stocks

### ISSUE THREAD

**Issue by sahiliitm** [dpguthrie/yahooquery#19]
Thanks for creating this amazing code repo. It is really useful!

Could you please also improve the documentation for which set of ticker symbols this is supposed to work with? It works with US stocks for me but not for indian stocks (I primarily invest in India). 

">>> tkr = Ticker('IDFCFIRSTB')
>>> tkr.financial_data
{'IDFCFIRSTB': 'Quote not found for ticker symbol: IDFCFIRSTB'}"
 
Can you please let me know whether this library is supposed to work for Indian stocks and if not, can you please document this as well as let me know how we can make it work for indian stocks?Would be happy to contribute!

**Comment by dpguthrie** [comment]
Any ticker symbol that’s available via Yahoo Finance should also be available through this API.  That symbol can be found if you append the exchange:

`tkr = Ticker(“IDFCFIRSTB.NS”)`
