### ISSUE TITLE
Only 1 quarter report received for balance sheet 

### ISSUE THREAD

**Issue by tanmaykhabia** [dpguthrie/yahooquery#194]
When fetching the balance sheet of ACC.NS only the latest quarter result came up instead of the historical result. 

**Expected behavior**
At least 4 quarters of historical data must be available. 

```python
import yahooquery as yf 
df = yf.Ticker("ACC.NS").balance_sheet(frequency='q' , trailing=False)
df.head()
```

**Screenshots**
![image](https://github.com/dpguthrie/yahooquery/assets/44644958/436fc17f-c267-42fb-80a1-b0a3a9db92a5)

**Desktop**
 - OS: Ubuntu 
 - Version 22.04

**Comment by ilibarra** [comment]
The YahooFinance quarterly balance table for ACC.NS is only one column, and values seem to match e.g. TangibleBookValue. If you refer to the annual table, try without `frequency='q'`
![image](https://github.com/dpguthrie/yahooquery/assets/2761796/0f46bc7d-9827-4d22-8fcd-cf9e347f365d)

**Comment by tanmaykhabia** [comment]
Looks like Yahoo does not have a very consistent system for storing historical data... for different companies. Thank for resolving this issue.
