### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by MarcSkovMadsen** [dpguthrie/yahooquery#2]
I would be nice if you wrote a bit in the docstring about what ' formatted' means. Is it because it returned as a DataFrame or does the data look "nice" in some way or ...?

![image](https://user-images.githubusercontent.com/42288570/72036601-963b2680-329b-11ea-9bbb-5e403c2d437a.png)

**Comment by dpguthrie** [comment]
I've updated the docstring with an explanation of formatted.
