### ISSUE TITLE
incomeStatementHistory get_modules data differs from income_statement()

### ISSUE THREAD

**Issue by krema** [dpguthrie/yahooquery#20]
**Describe the bug**
The incomeStatementHistory data using all_modules differs from income_statement() method call

**To Reproduce**

    ticker = Ticker('1FC.DE')
    result = ticker.get_modules('incomeStatementHistory')

vs.

    ticker = Ticker('1FC.DE')
    result = ticker.income_statement()

**Expected behavior**
The data should be the same.

**Screenshots**
![1E8EFD48-65D6-4277-88F5-1ED74C5498D4](https://user-images.githubusercontent.com/1336504/83974679-68f8b000-a8ef-11ea-8c5c-aca0a95f6b1d.jpg)

vs.

![C3B89395-7CEC-407D-99EE-71F6C91E01F5](https://user-images.githubusercontent.com/1336504/83974789-30a5a180-a8f0-11ea-8681-8f1bad84c7a6.jpg)

**Comment by dpguthrie** [comment]
This data _should_ be the same.  But, the data for each of those are coming from two separate endpoints.  The one used to populate the dataframe returned from the income_statement method is the one that is utilized through the YF front-end.  Why they're different is still a mystery to me.  I will continue to investigate, but I would recommend utilizing the income_statement, cash_flow, and balance_sheet methods in the meantime.

**Comment by rodrigobercini** [comment]
Just some more info: I did some investigation a few days ago and this inconsistency mostly affects non-US tickers. The ones I checked most thoroughly were from the Brazilian Stock Market and the pattern was quite erratic.

**Comment by dpguthrie** [comment]
This appears to be problematic for securities outside the U.S. and is an upstream issue with YF.  This issue is documented here:  https://yahooquery.dpguthrie.com/guide/ticker/modules/#all_modules.
