### ISSUE TITLE
adding protective code for Ticker.key_stats and Ticker.summary_profile 

### ISSUE THREAD

**Issue by galashour** [dpguthrie/yahooquery#214]
**Describe the bug**
I should clarify: 
So far, I saw the below issue for one ticker ('META'), possibly there are others, but for quite a few other tickers I didn't see this issue and is working perfectly fine.

Yet, for ticker 'META', I observed it seems that the call to Ticker('META') returns 'str' instead of 'dict' for the summary_profile and key_stats queries).

Even trying to add protective code using 'isinstance' (see below) triggers the exception (which I'm trying to bypass).

**To Reproduce**
```
yq = Ticker(ticker)
    ## << even the below defensive-check triggers an exception
    if isinstance(yq.summary_profile, dict):            
        yq_profile = yq.summary_profile[ticker] 
```

**Desktop (please complete the following information):**
 - OS: windows 11 (64 bits)
 - Browser : chrome
 - Python 3.11

1. My main question is whether there is a way to detect the issue before it causes an exception (as the above if statement apparently didn't do the trick).

2. May be good to check also why for this symbol ('META'), and possibly for some other symbols, these (dict) structures are missing to begin with.

**Comment by galashour** [comment]
not sure what changed (was just about to revert to a cumbersome try/except, when I saw it works today with no issue.

thnx.

**Comment by dpguthrie** [comment]
Closing out as this appears to be solved - feel free to reopen if you're still seeing problems.
