### ISSUE TITLE
Currency converter

### ISSUE THREAD

**Issue by willwill4000** [dpguthrie/yahooquery#215]
i am problem with using the currency_converter()  function to change the income statement from TWD to USD.

Please help

from yahooquery import Ticker

#Define the stock symbol
symbol = "TSM"

#Initialize the Ticker class with the stock symbol
tsm = Ticker(symbol)

#Fetch the income statement
income_statement = tsm.income_statement()

print(income_statement)

**Comment by dpguthrie** [comment]
The `currency_converter` function is no longer supported as it was severely limited by rate limiting.
