### ISSUE TITLE
I cannot get price module in Ticker class

### ISSUE THREAD

**Issue by RafaBarneto** [dpguthrie/yahooquery#237]
**Describe the bug**
From some days ago when I create Ticker class for any ticker, the modules price and summary details are missing. It seems only history module is working.

**To Reproduce**
This is my code:

from yahooquery import Ticker
ticker = 'VOYA'
emp = Ticker(ticker)
datos_diarios = emp.history(start=fecha_ini, end=fecha_fin,
                                    adj_ohlc=True)
info = {}
ticker = empresa.symbols[0]
info['nombre'] = emp.price[ticker]['shortName']
info['beta'] = float(emp.summary_detail[ticker]['beta'])

**Expected behavior**
I should have the Name of the company in info['nombre'] and beta in info['beta']
Instead I have a KeyError for the ticker ´VOYA´ in both cases.
Inspecting the content of emp instance, both methods "price" and "summary_detail" are missing.

**Screenshots**
I add screenshots for the above results.

<img width="1272" alt="Captura de pantalla 2023-11-11 a las 9 25 40" src="https://github.com/dpguthrie/yahooquery/assets/78498364/772fae43-0e2f-49a0-8c29-9f0115582adf">
<img width="489" alt="Captura de pantalla 2023-11-11 a las 9 24 54" src="https://github.com/dpguthrie/yahooquery/assets/78498364/6959495c-8a69-4622-ab6b-17c5ec09503e">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.0
 - Browser [safari]
 - Version [17]

**Comment by RafaBarneto** [comment]
Just to complete information, I use version 2.3.3 of yahooquery to get that result.

**Comment by alBronko** [comment]
I think I have the same issue.
I am outside the US so changed the \etc\hosts file to route query2.finance.yahoo.com to the hard ip 69.147.92.11.

```
>>> from yahooquery import Ticker
>>> all_financial_data_list = ['AccountsPayable', 'AccountsReceivable']
>>> ticker = Ticker("AAPL")
>>> ticker.get_financial_data(all_financial_data_list, frequency = 'q', trailing=False)
         asOfDate periodType currencyCode  AccountsPayable  AccountsReceivable
symbol
AAPL   2022-09-30         3M          USD     6.411500e+10        2.818400e+10
AAPL   2022-12-31         3M          USD     5.791800e+10        2.375200e+10
AAPL   2023-03-31         3M          USD     4.294500e+10        1.793600e+10
AAPL   2023-06-30         3M          USD     4.669900e+10        1.954900e+10
AAPL   2023-09-30         3M          USD     6.261100e+10        2.950800e+10

>>> ticker.price["AAPL"]
'Invalid Cookie'
>>> ticker.key_stats["AAPL"]
'Invalid Cookie'
```

this worked a few days ago and stopped all of a sudden. it doesnt work with a VPN to the US either.


Ubuntu 22.04
python 3.10 and 3.11 tested
yahooquery 2.3.3.

**Comment by RafaBarneto** [comment]
> I think I have the same issue. I am outside the US so changed the \etc\hosts file to route query2.finance.yahoo.com to the hard ip 69.147.92.11.
> 
> ```
> >>> from yahooquery import Ticker
> >>> all_financial_data_list = ['AccountsPayable', 'AccountsReceivable']
> >>> ticker = Ticker("AAPL")
> >>> ticker.get_financial_data(all_financial_data_list, frequency = 'q', trailing=False)
>          asOfDate periodType currencyCode  AccountsPayable  AccountsReceivable
> symbol
> AAPL   2022-09-30         3M          USD     6.411500e+10        2.818400e+10
> AAPL   2022-12-31         3M          USD     5.791800e+10        2.375200e+10
> AAPL   2023-03-31         3M          USD     4.294500e+10        1.793600e+10
> AAPL   2023-06-30         3M          USD     4.669900e+10        1.954900e+10
> AAPL   2023-09-30         3M          USD     6.261100e+10        2.950800e+10
> 
> >>> ticker.price["AAPL"]
> 'Invalid Cookie'
> >>> ticker.key_stats["AAPL"]
> 'Invalid Cookie'
> ```
> 
> this worked a few days ago and stopped all of a sudden. it doesnt work with a VPN to the US either.
> 
> Ubuntu 22.04 python 3.10 and 3.11 tested yahooquery 2.3.3.

Thanks alBronko.
I am also out of US, but let me confirm my understanding of your solution:
- It works right now or was just for some days/weeks?
- Where exactly make you the change and how?
Regards.

**Comment by alBronko** [comment]
I don't have a solution. Price doesn't work.

on linux, I added 
`69.147.92.11  query2.finance.yahoo.com`
to the file /etc/hosts

**Comment by kryp33** [comment]
It seems to stop working in US also a few hours ago. Hard to say if it is a temporary glitch or not. 
aapl = Ticker(['AAPL'])
aapl.quotes
>> 'Invalid Cookie'

**Comment by chfiii** [comment]
I've been seeing here in CT, US.  Started around 2:29PM EST.  the first problem I see is that https://fc.yahoo.com is returning a 502 error code.  It is saying that there's a problem and they are working to fix it.  The main finance.yahoo.com site is up though

**Comment by dpguthrie** [comment]
See if 2.3.4 fixes this for you.  Problems are largely location dependent unfortunately and may not provide the fix you're looking for.

**Comment by Rapid1898-code** [comment]
Hello - i tried to use the version 2.3.4 and still have the same error:

`{'AAPL': 'Invalid Cookie'}`

**Comment by danielegramola** [comment]
Same error here (Italy):

stock = Ticker('UCG.MI')
print(stock.key_stats)

Failed to obtain crumb. Ability to retrieve data will be significantly limited.
{'UCG.MI': 'Invalid Cookie'}

Python 3.11.7, Yahooquery 2.3.6
