### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement yahooquery==2.3.3 

### ISSUE THREAD

**Issue by af20** [dpguthrie/yahooquery#238]
In my Dockerfile I have

""""
FROM python:3.12 (tried also 3.08, 3.10)
RUN pip install -r requirements.txt

and in the file file 'requirements.txt':
[...]
yahooquery==2.3.3
[...]
"""

But I get the error:
ERROR: Could not find a version that satisfies the requirement yahooquery==2.3.3 (from versions: 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.3.0, 2.3.1, 2.3.2)

ERROR: No matching distribution found for yahooquery==2.3.3

Anyone can help?

**Comment by dkim777** [comment]
I have same problem on Raspberry Pi OS.
It can't find version 2.3.3
I have 2.3.2 currently.

**Comment by dkim777** [comment]
Still same.

sudo pip3 install yahooquery==2.3.4
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yahooquery==2.3.4
  Could not find a version that satisfies the requirement yahooquery==2.3.4 (from versions: 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.3.0, 2.3.1, 2.3.2)
No matching distribution found for yahooquery==2.3.4

**Comment by dkim777** [comment]
@dpguthrie I have Python 3.7.3  running on Raspberry Pi

**Comment by dpguthrie** [comment]
The current version of yahooquery (2.3.5) is restricted to >=3.8.1, <4.0.  Python 3.7.* is EOL.
