### ISSUE TITLE
v.2.3.6 fails to obtain a crumb for yahooquery.Research (or Ticker with username/password arguments).

### ISSUE THREAD

**Issue by ms82494** [dpguthrie/yahooquery#246]
**Describe the bug**
While I (located in the US) can obtain a crumb for a regular Ticker instance (without username or password arguments), creating a Research instance fails to obtain a valid crumb.
**To Reproduce**
```
(mmbase) luttensee:~ catweazle$ ipython
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os, operator

In [2]: import yahooquery as yq

In [3]: YUSER, YPASS = operator.itemgetter('YUSER','YPASS')(os.environ)

In [4]: ticker = yq.Ticker("AAPL")

In [5]: ticker.crumb
Out[5]: 'Tyha0f1R980'

In [6]: yq.__version__
Out[6]: '2.3.6'

In [7]: r = yq.Research(username=YUSER, password=YPASS)
Failed to obtain crumb.  Ability to retrieve data will be significantly limited.

In [8]: r.crumb

In [9]: 
```

**Expected behavior**
Successfully creating a Research/Ticker object that provides access to Yahoo Finance Plus features.
**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: macOS 14.1.2
 - Version [e.g. 22]: yahooquery 2.3.6, selenium 4.16

**Comment by dpguthrie** [comment]
It looks like Yahoo has implemented a recaptcha and a verification step that is not accounted for within the code, so it doesn't actually ever sign in.  I'm more than happy to accept a PR that implements this functionality but I won't be able to fix this.

**Comment by ms82494** [comment]
For me the problem seems to have been even simpler. I didn't have ```webdriver-manager``` installed. Or the wrong version of it. Everything seems to be fine.
