### ISSUE TITLE
Yahoo Finance instituting recaptcha

### ISSUE THREAD

**Issue by me1029134** [dpguthrie/yahooquery#251]
**Is your feature request related to a problem? Please describe.**
The current problem seems to be a recaptcha check with Yahoo Premium. Seems to be a new issue as of a couple weeks. 

This is the Error I'm getting when trying this:
query = yq.Ticker('AAPL', username= "UserEmail", password="PW")

Error:
DevTools listening on ws://127.0.0.1:49914/devtools/browser/61cb5ef2-a79d-4ac3-9a83-d1965b9d7ca0
[1226/162343.913:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[1226/162347.095:ERROR:gl_utils.cc(412)] [.WebGL-000029B000E73F00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): 
GPU stall due to ReadPixels
Unable to login and/or retrieve the appropriate cookies.  This is most likely due to Yahoo Finance instituting recaptcha, which this package does not support.

**Describe the solution you'd like**
I think we can either import the cookie information. Or have the user login if the cookie information is not there. 

**Describe alternatives you've considered**
Maybe there is another more common way around this. Or another library has already figured this out with Premium Yahoo Users, that we can maybe work from. 

**Additional context**
Thank you!

**Comment by dpguthrie** [comment]
I made a [comment in this issue](https://github.com/dpguthrie/yahooquery/issues/246#issuecomment-1849237487) - tldr; i'm not going to work on instituting recaptcha but am more than willing to accept a PR.  Easiest solution, I think, would be to accept cookies as a keyword argument to initializing a `Ticker` and putting the responsibility on the user to passing the appropriate cookies that indicate a logged in user.

**Comment by me1029134** [comment]
Actually it looks like maybe it's working for me after all.... I guess there was a hidden character in my username.
'what@​gmail.com' There is a space between the @ and g and you can only see it if you arrow key through it.... I've never seen that before. (I wonder if that will show up when I post this, still confused about that)

I did:
query = yq.Ticker('AAPL', username= "UserEmail", password="PW")
query.p_income_statement(frequency="q") # With the "p_"

I'm still getting these messages on the terminal:
DevTools listening on ws://127.0.0.1:60308/devtools/browser/c6b5159d-1699-491c-a2a6-74c3616bc6ed
[1226/164306.950:ERROR:gl_utils.cc(412)] [.WebGL-0000111400E85400]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): 
GPU stall due to ReadPixels
[1226/164308.709:ERROR:gl_utils.cc(412)] [.WebGL-00001114026F4D00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): 
GPU stall due to ReadPixels

But I'm getting what I want at least. Thank you.
