### ISSUE TITLE
grading_history seems returning empty fields

### ISSUE THREAD

**Issue by vaclavku** [dpguthrie/yahooquery#252]
Hi, could you please check: grading_history?
Seems it returns empty data. 
Many thanks.

**Comment by dpguthrie** [comment]
For any future issues you do open - be more specific, provide some code examples, and (in this case) a screenshot of YF of the data you expect to see.  I'm inclined to close this though based on the lack of specificity and this:
<img width="683" alt="image" src="https://github.com/dpguthrie/yahooquery/assets/10198967/1a89274e-2596-438c-99a9-d4132699e7b6">

**Comment by vaclavku** [comment]
Hello, many thanks. It seems working now.
