### ISSUE TITLE
Problem with new release 2.3.7

### ISSUE THREAD

**Issue by RafaBarneto** [dpguthrie/yahooquery#253]
Since some weeks ago yahooquery do not work because it do not get any data. I use it in Spain and saw yesterday the new release 2.3.7, apparently to resolve the problem related with access from EU; but now I get a very strange error because apparently the module "tqdm" is not installed. But I check it by at least 3 ways and it is installed with the version 4.66.1

I am using Spyder IDE in a Mac under Anaconda environment. The env is named "Nueva_base" and the behaviour is illustrated this way:

The error message in Spyder:
<img width="1037" alt="Captura de pantalla 2023-12-29 a las 12 11 42" src="https://github.com/dpguthrie/yahooquery/assets/78498364/98ffda18-ba4e-405c-b0f3-ab557d3222c5">

The result of pip freeze in the Spyder terminal:
<img width="1040" alt="Captura de pantalla 2023-12-29 a las 12 12 14" src="https://github.com/dpguthrie/yahooquery/assets/78498364/c363573e-f235-4bb4-b986-590ed5621cb8">

The installed packages in Anaconda "Nueva_Base" env:
<img width="1395" alt="Captura de pantalla 2023-12-29 a las 11 57 42" src="https://github.com/dpguthrie/yahooquery/assets/78498364/87f4575d-37bf-4acd-b9a8-a4d62ceec14f">

My environment:
 - OS: MacOS Sonoma 14.2.1
 - Spyder 5.4.3
 - Anaconda 2.2.0

**Comment by ibart** [comment]
pip install tqdm

**Comment by ibart** [comment]
> Since some weeks ago yahooquery do not work because it do not get any data. I use it in Spain and saw yesterday the new release 2.3.7, apparently to resolve the problem related with access from EU; but now I get a very strange error because apparently the module "tqdm" is not installed. But I check it by at least 3 ways and it is installed with the version 4.66.1
> 
> I am using Spyder IDE in a Mac under Anaconda environment. The env is named "Nueva_base" and the behaviour is illustrated this way:
> 
> The error message in Spyder: <img alt="Captura de pantalla 2023-12-29 a las 12 11 42" width="1037" src="https://private-user-images.githubusercontent.com/78498364/293354196-98ffda18-ba4e-405c-b0f3-ab557d3222c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTM2NTEsIm5iZiI6MTcwMzg1MzM1MSwicGF0aCI6Ii83ODQ5ODM2NC8yOTMzNTQxOTYtOThmZmRhMTgtYmE0ZS00MDVjLWIwZjMtYWI1NTdkMzIyMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyMzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNjc2Zjg1ZDliOGM5OTJiNzVkYzgxOTA1YjRhZTVlMGY2YmIzMDVhMjUyMGRjMmVhMTA1YmExM2M5YzM0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fQA005Bdytd6JNykLgBKoWnO0AcmTro7IMu_kODiQWA">
> 
> The result of pip freeze in the Spyder terminal: <img alt="Captura de pantalla 2023-12-29 a las 12 12 14" width="1040" src="https://private-user-images.githubusercontent.com/78498364/293354485-c363573e-f235-4bb4-b986-590ed5621cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTM2NTEsIm5iZiI6MTcwMzg1MzM1MSwicGF0aCI6Ii83ODQ5ODM2NC8yOTMzNTQ0ODUtYzM2MzU3M2UtZjIzNS00YmI0LWI5ODYtNTkwZWQ1NjIxY2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyMzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NmIxMzIxZDYwZjhkYzkwOGI4OTAyMDFiZDdlMjc0NTBkNGRkODBkMTA2ZWVkYTk1MGUwYzMwN2MwMDUzOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vZyu-vjPRVyYAdzZL-9Kbs3I3XmD6sOr7yw5GazDwIs">
> 
> The installed packages in Anaconda "Nueva_Base" env: <img alt="Captura de pantalla 2023-12-29 a las 11 57 42" width="1395" src="https://private-user-images.githubusercontent.com/78498364/293354723-87f4575d-37bf-4acd-b9a8-a4d62ceec14f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTM2NTEsIm5iZiI6MTcwMzg1MzM1MSwicGF0aCI6Ii83ODQ5ODM2NC8yOTMzNTQ3MjMtODdmNDU3NWQtMzdiZi00YWNkLWI5YTgtYTRkNjJjZWVjMTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyMzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGI0OTc0NjA3MWJlOTdmNDQ4YmIwYWI2YjAyNzVmOWVlOGU0YzE2YTg5ZDA4ZjlkNGJiNTJiZGRkMjhjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESGw7-Pkxo8-YRUr43nWchw6m-l7JFMfPBM0nd8fl-A">
> 
> My environment:
> 
>     * OS: MacOS Sonoma 14.2.1
> 
>     * Spyder 5.4.3
> 
>     * Anaconda 2.2.0

`pip install tqdm
`
