### ISSUE TITLE
Please support data from Beijing Stock Exchange of China

### ISSUE THREAD

**Issue by qkxie** [dpguthrie/yahooquery#257]
**Is your feature request related to a problem? Please describe.**

Yes. I cloud not get any data from Beijing stock exchange of china.

**Describe the solution you'd like**

Cloud get data from stock code like "33452345.BJ“

**Describe alternatives you've considered**

No

**Additional context**

```python
from yahooquery import Ticker

code = '836547.BJ'
stock = Ticker(code, proxies=self.proxies)
df = stock.history(period='7d', start=aim_date, end=aim_enddate, interval='1d')
```

the `df` is an empty dataframe.

**Comment by RudyNL** [comment]
You can only retrieve data from stocks which are available on Yahoo Finance.
Use the page https://finance.yahoo.com/lookup to check the availability.
Your particular stock `33452345.BJ` and `836547.BJ` are not available, so its not a problem of `yahooquery` but of Yahoo Finance
