### ISSUE TITLE
Yahoo Finance API -> yahooquery -> UK

### ISSUE THREAD

**Issue by mtremlett** [dpguthrie/yahooquery#259]
From the 20-DEC-23, the Yahoo Finance API (using yahooquery) has stopped working for the UK. 

I have python code that uses yahooquery to pull "fund_top_holdings" data for a list of funds/ETFs, that worked fine up until that date. 

To diagnose, I have tried python 3.11 & 3.12 and yahooquery 2.3.4, 2.3.5 & 2.3.7. No permutation works. 

The code only works if I VPN as "USA" at which point it takes 10x longer to run.

Is there a yahooquery workaround ? Are there any other options? 

_Many thanks in advance..._

**Comment by RudyNL** [comment]
Many times similar signals are posted. Personally I believe that for most European users `yahooquery` is working fine from v2.3.7.
I don't have had any problems after the introduction of v2.3.7.
Yahooquery         2.3.7
Python                 3.10.12
Beautifulsoup4     4.12.2
Numpy                  1.26.1
Pandas                 2.1.3
Location: Netherlands
It might that the UK is taking a special position, outside the USA and not in the EU anymore. You could try a VPN into the EU instead.

**Comment by ibart** [comment]
> _Please see detail below....it's defintiely an EU thing ...Any other workaround other than VPN as USA?_
> 
> Works: USA, Australia, India,
> 
> Does not work: UK, Netherlands, France, Ireland, Switzerland
> 
> import yahooquery as yq
> 
> FUND_LIST = ['SPY','QQQ','VUAG.L']
> 
> MyFund=yq.Ticker(FUND_LIST, validate=True, asynchronous=True)
> 
> top_holdings = MyFund.fund_top_holdings
> 
> print(top_holdings)
> 
> > pip show yahooquery
> > Name: yahooquery
> > Version: 2.3.7
> 
> Error message snippet....
> 
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v1/test/getcrumb (Caused by ResponseError('too many 500 error responses'))
> 
> ...
> 
> requests.exceptions.RetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v1/test/getcrumb (Caused by ResponseError('too many 500 error responses'))

remove asynchronous=True

**Comment by mtremlett** [comment]
THAT WORKED !!!   _...thank you so much._
