### ISSUE TITLE
Can't login to access premium features

### ISSUE THREAD

**Issue by Gustav91** [dpguthrie/yahooquery#26]
I have a premium account, but I'm not able to login. I have tried both:

`tickers = Ticker('ABB.ST', username=<user>, password=<pw>)`
and
`tickers = Ticker('ABB.ST')`
`tickers.login(<user>, <pw>)`

I get the following error:
Message: no such element: Unable to locate element: {"method":"link text","selector":"Finance"}
  (Session info: headless chrome=81.0.4044.92)

I have tried both chrome/chromedriver 81 and 84.

I'm running ubuntu 18.04 and python 3.6.9.

This api is exactly what I have been looking for and if I could get it to work I would be very grateful.

**Comment by dpguthrie** [comment]
Which version are you using?  You might be able to get around that if you upgrade to the newest version - 2.2.5.  If that doesn't work, it most likely means Yahoo has detected that you're using selenium to login and is enforcing an extra step.  And unfortunately, I've only been able to manually get around this issue.  Try the following if upgrading the version doesn't work:

```
driver = webdriver.Chrome()
driver.execute_script("window.open('{}');".format("https://login.yahoo.com"))
```

When you get to the login page, login as you normally would.  After you submit your password, my guess is you'll reach an extra step, confirming you're not a robot.  Once you've proceeded through that, you should be logged in.  Close the selenium browser.  

Now, try utilizing yahooquery to login and I'm pretty sure it should work for you.

Obviously, this is not a great workaround, so I'm still looking for solutions.  If you have any, please feel free to submit a pull request.

I haven't tried this solution but found it searching for answers:
https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver

**Comment by Gustav91** [comment]
Sorry that I missed providing the version, I used 2.2.5.
I tried the code snipped that you suggested and actually there is no extra "not a robot" step and login works.

I don't really understand what the purpose of:
```
try:
    self.driver.find_element_by_xpath('//a[@href="https://finance.yahoo.com/"]').click()
except NoSuchElementException:
    self.driver.find_element_by_link_text('Finance').click()
```
is in login.py, is it to verify that the user is logged in?
When looking around the page after login I actually can't see any link to yahoo finance, it just looks like I'm logged in to "normal" yahoo so  I'm guessing that could be a reason for it to fail.
I tried to remove the above code and after that I can use functions such as p_income_statement successfully.

**Comment by dpguthrie** [comment]
Interesting.  When I initially wrote this, it seemed like the appropriate cookies were not set **until** I navigated to the finance page.  And, if I didn't do that, all requests to the premium endpoints were unsuccessful.  I'm going to test this on my end as well and see if we can just take it out altogether.  You are right though about the try / except block.  It's unnecessary and just essentially a holdover from when I was trying stuff.  Thanks for digging a little deeper into this.

**Comment by Gustav91** [comment]
Aha then I understand. Maybe the try/except could just be replaced with something like
`self.driver.get("https://finance.yahoo.com/")`
if there are cases when it's necessary to navigate to finance page.

**Comment by dpguthrie** [comment]
Well, I'm not sure it's necessary anymore.  I just took out the same code you did and tried to access premium data and it worked.  So, I'm thinking just take it out entirely.

**Comment by dpguthrie** [comment]
I removed the unnecessary code in 2.2.6.  I believe if you upgrade, this issue will be resolved.

**Comment by Gustav91** [comment]
Yep, thanks it works fine now!
I'll close the issue.
