### ISSUE TITLE
Option_chain not returning any data

### ISSUE THREAD

**Issue by BaptistePaulD** [dpguthrie/yahooquery#261]
I have a basic Python script pulling option prices for selected tickers at regular interval and feed it to a SQL db. 

From Thursday 01/24/2024, some of the tickers have stopped returning data. 
on Friday none of my ticker where returning any option data. 

I did a test on Tesla's option as follow

`from Yahooquery import Ticker`
`df =Ticker('TSLA')`
`df.option_chain `
`print(df.head())` 

it returns 'No option chain data found'
however, looking at the options on Yahoo's page i have a few hundred.
https://ca.finance.yahoo.com/quote/TSLA/options?p=TSLA

**Comment by pydazhang** [comment]
same issue, same returns

**Comment by nehctuk** [comment]
I am seeing the same issue, looks like it is erroring out from not being signed in.

**Comment by wingr** [comment]
I am also seeing the same issue. @nehctuk did you find a way around the error?

**Comment by ms82494** [comment]
It works for me.
@BaptistePaulD: You mistakenly capitalized `yahooquery` in your code. And since you defined `df` as a Ticker instance, it doesn't have a head() method.

**Comment by nehctuk** [comment]
@wingr No, I am still seeing errors like this currently. Not sure what the cause is.
<img width="513" alt="Screen Shot 2024-02-13 at 5 55 58 PM" src="https://github.com/dpguthrie/yahooquery/assets/19308156/db3e8443-79ae-47b0-abb3-9f1ba13d6372">

**Comment by nehctuk** [comment]
upgrading from 2.3.2 to 2.3.7 fixed the issues for me

**Comment by wingr** [comment]
> upgrading from 2.3.2 to 2.3.7 fixed the issues for me

Nice! I will give that a try - thank you @nehctuk!

**Comment by BaptistePaulD** [comment]
> upgrading from 2.3.2 to 2.3.7 fixed the issues for me

It worked for me too. Thanks for the help team!
