### ISSUE TITLE
Ticker Validation Module not working properly 

### ISSUE THREAD

**Issue by MarkWClements** [dpguthrie/yahooquery#27]
I recently installed version 2.2.5 of yahooquery and the new .validation feature does not seem to be working properly.

Here is a minimum working example in which I check the validity of the S&P 500 ETF tickers and one that I made up.

    from yahooquery import Ticker

    tickers_to_test = ['IVV','SPY','MWCXYZ']

    Valid_Tickers = pd.DataFrame(columns={'Ticker','Valid'})

    # Validate Tickers
    for ticker in tickers_to_test:
        test = Ticker(ticker)
        Valid_Tickers = Valid_Tickers.append({'Ticker':ticker, 'Valid':test.validation}, ignore_index=True)

    print(Valid_Tickers)

Here is the output

![Screen Shot 2020-07-24 at 3 44 04 PM](https://user-images.githubusercontent.com/21218415/88441214-48b08200-cdc5-11ea-8ae7-52eacb96d804.png)

I would expect a data frame with "True" (or whatever the code uses to indicate a valid ticker for the first two) withe "None" for the made up ticker. The yahooquery package downloads historical data fine for  the 'IVV' and 'SPY' tickers so I know that they are valid.

Thank You

**Comment by dpguthrie** [comment]
Nothing is returned from calling that property.  It does a couple things:

1. Validate symbols when instantiated.  You can pass validate=True to the Ticker class and it will validate each symbol that was passed. If an invalid symbol is detected, it will be stored in the invalid_symbols property.  Only valid symbols will remain in the symbols property.

2. You can also call that property after the class has been instantiated and it will do the same thing.

Also, it’s best used when passing in a large list of symbols.

**Comment by MarkWClements** [comment]
Ah got it. It would be helpful to add a more detailed description of this property in the readme and also mention the invalid_symbols property.  One unrelated question: are the inception dates for ETFs stored in the Ticker class somewhere?

Thanks for your help

**Comment by dpguthrie** [comment]
I’m currently working on some better documentation.  You can find the inception date with the key_stays property.

**Comment by MarkWClements** [comment]
Ok awesome. Can you give me an example of how I would access the key_stays property from the yahooquery.ticker.Ticker object? It's not clear to me how to access this property when I'm passing the Ticker class a large list of symbols.

**Comment by dpguthrie** [comment]
Sure...

```
from yahooquery import Ticker

t = Ticker([your list of symbols])
stats = t.key_stats
```
The `stats` variable is a dictionary.  Each of the symbols you passed in your list will be a key in the dictionary.

```
# validate your list
t = Ticker([...], validate=True)

# validate and run asynchronously
t = Ticker([...], asynchronous=True, validate=True
```

**Comment by MarkWClements** [comment]
Thank you!

When you pass `proxies={http: ..., https: ...}` to the `Ticker` class, is this a dictionary? If so, does that mean it can only take two proxy servers (an http and an https one) since there will only be two unique keys in this dictionary?

Also, how does the code handle multiple proxy servers? Does it split up the asynchronous requests across all the proxy servers given to the `proxies` object passed to the `Ticker` class?

Could you give me an example of how to use this and how to pass multiple proxy servers?

Thanks.

**Comment by dpguthrie** [comment]
We've already ventured outside the scope of this particular issue, which I've been happy to help you with.  If you'd like to open another issue related to the proxy use, feel free to do so.  You can also view some of the documentation related to the [requests](https://requests.readthedocs.io/en/master/user/advanced/#proxies) package, which yahooquery relies heavily on.
