### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ScottSauers** [dpguthrie/yahooquery#272]
I believe this is new. I will try to fix this.

Here is the issue:
```
/opt/homebrew/lib/python3.12/site-packages/yahooquery/utils/__init__.py:1470: FutureWarning: 'S' is deprecated and will be removed in a future version. Please use 's' instead of 'S'.
  has_live_indice = index_utc[-1] >= last_trade - pd.Timedelta(2, "S")
/opt/homebrew/lib/python3.12/site-packages/yahooquery/ticker.py:1333: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["dividends"].fillna(0, inplace=True)
```

The s warning comes from utils, ```__init__.py```. The other from ticker.py.

I fixed the issue in the source code and it now runs without warning.

Pull request here: https://github.com/dpguthrie/yahooquery/pull/273

**Comment by maread99** [comment]
Hi @ScottSauers

I believe both the warnings you've noted are resolved by the PR #262, which I see you've commented on.

Please advise of any other lines that are causing any deprecation warnings (i.e. other than `/utils/__init__.py:1470` and `/ticker.py:1333`).

Thanks
