### ISSUE TITLE
growth estiamte

### ISSUE THREAD

**Issue by SoftDevDanial** [dpguthrie/yahooquery#29]
hi , Is there a way to get growth estimate of a company under analysis tab?

![image](https://user-images.githubusercontent.com/64815604/88708697-a25ad880-d146-11ea-9c84-b481bf021b1d.png)

![image](https://user-images.githubusercontent.com/64815604/88708662-9111cc00-d146-11ea-976f-4e93b4d96473.png)

**Comment by dpguthrie** [comment]
Take a look at the `earnings_trend` property.

```
from yahooquery import Ticker
import pandas as pd

msft = Ticker('msft')
data = msft.earnings_trend

df = pd.DataFrame(data['msft']['trend'])
df[['endDate', 'period', 'growth']]

      endDate period   growth
0  2020-09-30     0q  0.11600
1  2020-12-31    +1q  0.06600
2  2021-06-30     0y  0.12200
3  2022-06-30    +1y  0.13500
4        None    +5y  0.15000
5        None    -5y  0.18174
```

**Comment by SoftDevDanial** [comment]
oh how did i miss that .. this is what i wanted thanks a lot!
