### ISSUE TITLE
Feature Request: Remove "_" from _PERIODS, _INTERVALS, _ENDPOINTS.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [dpguthrie/yahooquery#3]
I think it's natural for a user of the package to use the _PERIODS, _INTERVALS, _ENDPOINTS names in the code. But the "_" makes them protected, i.e. not intended for public use.

Solution: remove "_" and make them public.

#### Additional Context

Linters complain about them being protected.

![image](https://user-images.githubusercontent.com/42288570/72038492-df8e7480-32a1-11ea-9107-e346e27da7d0.png)

**Comment by dpguthrie** [comment]
Thanks for the tip.  I've changed them to public attributes.
