### ISSUE TITLE
Message: 'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by moe18** [dpguthrie/yahooquery#31]
Trying to get access to my premium account data and keep on getting this error Message: 'chromedriver' executable needs to be in PATH

1. Run Research(username='username', password='password')

**Expected behavior**
get the research data from yahoo finance premium account 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser chrome

**Comment by dpguthrie** [comment]
You need to either include the chromedriver executable in your PATH (you can follow this [tutorial](https://www.kenst.com/2015/03/including-the-chromedriver-location-in-macos-system-path/)).  Or you can save the executable in the expected location for your OS, which for Mac I believe is [usr/local/bin](https://stackoverflow.com/a/57531596/3456446).
