### ISSUE TITLE
Not able to get data of scrips containing '&' symbol

### ISSUE THREAD

**Issue by Akshaysat** [dpguthrie/yahooquery#33]
![git_issue](https://user-images.githubusercontent.com/23153879/90599952-61208a80-e213-11ea-9305-08c772dbe498.PNG)

I am not able to read data of scrips with '&' symbol for Indian stock market. It ssems to be reading only letters after '&' symbol.

**Comment by dpguthrie** [comment]
I will fix that in the next release (2.2.7), which should be out by the end of the week.  You can get around that in the meantime if you pass it as a list.

```
data = Ticker(['L&TFH.NS'])
```

**Comment by Akshaysat** [comment]
Thanks for the quick reply and solution.
