### ISSUE TITLE
Dividend data

### ISSUE THREAD

**Issue by frogger72** [dpguthrie/yahooquery#34]
Thanks for this awesome project. This is a must-have feature for a lot of investors including myself. The most important is Forward Annual Dividend Date, as seen here:

https://finance.yahoo.com/quote/aapl/key-statistics?ltr=1

Please let me know if it's already implemented and I missed it.

**Comment by dpguthrie** [comment]
Yeah, that one's a little tough to find as it's not labeled with "forward".  You can find that in the `summary_detail` property.  Also, you can use the search functionality within the documentation to help as well:

![image](https://user-images.githubusercontent.com/10198967/91253124-5c306f00-e71c-11ea-9db8-8190ec1a5e88.png)

**Comment by frogger72** [comment]
Thanks! I realized I was missing it because I was trying a ticker without a dividend (in which case, key is missing instead of value being null).

**Comment by cmjordan42** [comment]
Lightly related so will try adding this question on here. I have not been able to find next dividend amount in `yahooquery`, only projected/annualized dividend rates/yields. As an example, the number I'd be looking for in this screenshot is $1.02 
![image](https://github.com/dpguthrie/yahooquery/assets/10622378/61ffc945-ec5d-486e-b79b-08fb7b068107)

Is this available somewhere?
