### ISSUE TITLE
Ticker list should be an Iterable not forced to be a strict list type

### ISSUE THREAD

**Issue by shipmints** [dpguthrie/yahooquery#37]
Using a Python set should be allowed as a symbol list, not just a strict list type. Any Iterable should be acceptable to the interface. For now, I'm forcing our symbol sets to a list to conform to the list interface.

In base.py:

```
    @symbols.setter
    def symbols(self, symbols):
        self._symbols = _convert_to_list(symbols)
```

In util.py:

```
def _convert_to_list(symbols, comma_split=False):
    if isinstance(symbols, list): # WHY JUST A LIST? 
        return symbols
    if comma_split:
        return [x.strip() for x in symbols.split(',')]
    return re.findall(r"[\w\-.=^&]+", symbols)
```

Better might be to test for string and assume iterables and let them fail naturally if they are not.

```
def _convert_to_list(symbols, comma_split=False):
    if isinstance(symbols, str):
        if comma_split:
            return [x.strip() for x in symbols.split(',')]
        else:
            return re.findall(r"[\w\-.=^&]+", symbols)
    else:
        return symbols
```

Thanks, again.

**Comment by dpguthrie** [comment]
Thanks @shipmints for creating this issue (and the others as well).  This seems to be a good thing to add to the package and relatively easy as well; I'll include it in the next relase.

**Comment by dpguthrie** [comment]
This is allowed now in 2.2.8.

**Comment by shipmints** [comment]
Great, thank you. I'll check it out and update my code when I next pull a release update.
