### ISSUE TITLE
Ticker.History bug maybe?

### ISSUE THREAD

**Issue by SoftDevDanial** [dpguthrie/yahooquery#38]
Hi , I am using Ticker.History for a project. How do i retrieve the last 60 days for "5m" interval excluding weekends as currently i can only retrieve the last 40 days since it includes weekends. Example , if i use the last 60 business days from now which is ,2020-06-22 , this error pops up _"5m data not available for startTime=1592755200 and endTime=1598745086. The requested range must be within the last 60 days."_ , but if i change it to 2020-07-02 which includes weekends, no error would pop out.

**60 Business Days**
```
stockyq = Ticker(tick)
price = stockyq.history(interval = "5m" , start = "2020-06-22", end = None)

```

**Error**
`"MSFT": "5m data not available for startTime=1592755200 and endTime=1598745086. The requested range must be within the last 60 days."`

The data returned excludes weekends but instead of getting 60 business days data , i get 40-45 business days data. Is this intentional or is it a bug?

**Comment by dpguthrie** [comment]
Unfortunately, the 60 days is not referring to business days.  That's a constraint (and error message) given from Yahoo Finance, not this library.

**Comment by SoftDevDanial** [comment]
I guess we need to do our own way of getting the 60 business days. 

Thanks for the quick reply!
