### ISSUE TITLE
Financials functions are returning 404 errors.

### ISSUE THREAD

**Issue by hprovias** [dpguthrie/yahooquery#39]
Firstly, love the tool! I recently noticed that all of my uses of the functions to retrieve financial data for a stock are returning 404 errors. For example, ticker.cash_flow(), ticker.income_statement(), ticker.balance_sheet() all return the error. But ticker.summary_detail does not for some reason.

Here is my test code which I ran to generate the error.
![image](https://user-images.githubusercontent.com/70626498/91942877-e21e5e00-ecb8-11ea-827b-31ee684db5f3.png)

When run, it returns the result below:
![image](https://user-images.githubusercontent.com/70626498/91942811-c7e48000-ecb8-11ea-966b-31c41240297e.png)

As you can see in the image, summary_detail returned data but the functions regarding financials returned errors.

I ran the same code last night it it was working with no issue so there is some confusion regarding that, Any insights would be much appreciated.

Best Regards

**Comment by huima22** [comment]
I also start having the same 404 issue with get financial data function. i can see ticker has data but after query, it returns 404

**Comment by dpguthrie** [comment]
This appears to be an issue on the Yahoo Finance side. 

![image](https://user-images.githubusercontent.com/10198967/91987776-b7013200-eceb-11ea-8cbd-1aa6ff0df8b9.png)

![image](https://user-images.githubusercontent.com/10198967/91988240-46a6e080-ecec-11ea-88d0-f39f441edfb3.png)

You can see from the image above that those URLs are returning 404 even on the Yahoo Finance front-end.  I'll keep checking and will update this thread with anything I find out.

**Comment by dpguthrie** [comment]
In the meantime, you can use the `get_modules` method to return income statement, balance sheet, and cash flow data.  The data returned will be in a dictionary, but you can easily get it into a dataframe:

```python
module = "incomeStatementHistory"  # retrieves annual income statement data

aapl = Ticker('aapl')
data = aapl.get_modules(module)
df = pd.DataFrame(data['aapl'][module])
```

Couple things with this though:
- Companies outside the U.S. can have inaccurate data
- The amount of data returned will be less (no TTM data and not as many items)

See more modules in the [documentation](https://yahooquery.dpguthrie.com/guide/ticker/modules/#get_modules)

**Comment by huima22** [comment]
get financial seems work now. thanks for answering

**Comment by dpguthrie** [comment]
This appeared to be a YF issue, so I'm going to close this.  Feel free to reopen if you notice any other issues.
