### ISSUE TITLE
available financials variables

### ISSUE THREAD

**Issue by rschuech** [dpguthrie/yahooquery#4]
Hi Doug,

I am just getting started using your very useful code and have a small question - it seems that not every financials entry visible on the Yahoo finance website is returned by the code.  For instance on the balance sheet (for AAPL for instance), under Property, plant and equip, the code returns Net property, plant and equipment but not Gross property, plant and equipment or Accumulated Depreciation.  I could easily be missing something but just wondering if this is by design, a limitation of the unofficial API, etc.  Thanks for any thoughts!

Rudi

**Comment by dpguthrie** [comment]
Thanks for letting me know, Rudi.  You are correct, though.  That data, for some reason, is not available through that endpoint.  I'm going to do a little more research and will let you know what I find.

**Comment by dpguthrie** [comment]
@rschuech  Try the newest version and see if your issue is resolved. I think it should be.
