### ISSUE TITLE
Progress reporting would be nice

### ISSUE THREAD

**Issue by shipmints** [dpguthrie/yahooquery#40]
When downloading a large amount of data, even in batches, for example S&P500 constituents, S&P400 (mid-cap), ETFs, indexes, etc. it would be nice for the library to report some kind of progress during processing lists of symbols. This could be https://github.com/tqdm/tqdm or a callback or whatever people think would be good.

**Comment by dpguthrie** [comment]
Yeah, I think that's a reasonable addition to the library.  I think tqdm could be a good option as it fits pretty well into the existing codebase and the user can toggle whether or not they'd like to see it.  The user can either add it as a keyword argument to the `Ticker` class:

```python
t = Ticker(symbol_list, progress=True)
```
Or on the instance itself:

```python
t.progress = True
```

Of course, I'm open to suggestions though if anyone has a better idea.

**Comment by dpguthrie** [comment]
The newest version, 2.2.8, contains the functionality for a progress bar.  Use the syntax above to add the progress bar or check out the [documentation](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#progress).

**Comment by shipmints** [comment]
Great, thank you. I'll check it out and update my code when I next pull a release update.
