### ISSUE TITLE
News function not returning the latest articles

### ISSUE THREAD

**Issue by hgjlee** [dpguthrie/yahooquery#44]
The news function is not returning the latest articles. It worked fine a few days ago, but since yesterday, it seems like the latest articles are somehow filtered out. Do you have some clues as to why this is happening?

**Comment by dpguthrie** [comment]
At first glance, I would say that they may have discontinued the use of that endpoint.  I can't actually see anywhere within a ticker's page that they're making any requests to that endpoint.  I'll do a little more research, but I may have to find a different way to retrieve the news items.

**Comment by hgjlee** [comment]
That makes sense. Please let me know when you figure that out. I appreciate it.

**Comment by peterferguson** [comment]
Any updates on this?

**Comment by dpguthrie** [comment]
From what I can see, there's no way to get this data.  Happy to accept a PR if anyone finds an alternative.
