### ISSUE TITLE
pip dependencies are too restrictive and cause incompatibility issues

### ISSUE THREAD

**Issue by shipmints** [dpguthrie/yahooquery#46]
Hi, Doug,

The latest requirements.txt says:
```
lxml==4.5.0
pandas>=0.24
requests-futures==1.0.0
selenium==3.141.0
tqdm==4.48.2
```

It is better to, instead, I think, use minimum versioning to allow yahooquery to coexist with other packages that share the same dependencies. The ones I've seen use relative rather than absolute versions.

Perhaps this:

```
lxml>=4.5.0
pandas>=0.24
requests-futures>=1.0.0
selenium>=3.141.0
tqdm>=4.48.2
```

These changes are preventing our team from upgrading yahooquery as we have dependencies that mandate lxml >= 4.5.1.

I'd also suggest making selenium optional if it's not needed by the default functionality i.e. without a premium subscription?

**Comment by dpguthrie** [comment]
Both are reasonable requests.  I actually thought I was going to run into this issue eventually.  I'll get a fix out quickly.  Thanks again for contributing here and helping to make this package better.

**Comment by shipmints** [comment]
Hi, Doug, it would be good to iron these out sooner than later. We have to keep overriding these manually and it's kind of a pain in the neck.

**Comment by dpguthrie** [comment]
Yep.  My bad...dropped the ball on this one.  I'll try and update it soon.  I did change the file in the repo though if you want to install from here.

**Comment by dpguthrie** [comment]
Try installing 2.2.9

**Comment by shipmints** [comment]
Good quick edit on the release number... I had tried before the last package was yanked. I knew to wait.

The new one installs fine now next to other packages with the same dependencies. Thanks, again.
