### ISSUE TITLE
premium access

### ISSUE THREAD

**Issue by rschuech** [dpguthrie/yahooquery#5]
Hi Doug,

Another small question:  any way / plans to include the ability to access the additional data included in a Premium account?  I suspect the answer is no (also seems the case for yfinance) but worth asking!  (I don't even have a Premium account currently, just thinking about future options).

Thanks,
Rudi

**Comment by dpguthrie** [comment]
I don't have a premium account either but I have looked at ways to retrieve that data.  I think if login functionality is easy to add to the package (as you'll need a userId to make requests), then additional premium endpoints should be relatively easy to add.  I will look at for upcoming releases.

**Comment by dpguthrie** [comment]
@rschuech the newest version, 2.0.0, has premium access. Sign up for a free trial on YF and view the README to see how to access premium data.
