### ISSUE TITLE
historical financial

### ISSUE THREAD

**Issue by zhenyulin** [dpguthrie/yahooquery#50]
**Is your feature request related to a problem? Please describe.**
Ticker. all_financial_data() or related methods can return financial data of more than 4 quarters or 3 years. 

**Describe the solution you'd like**
Ticker.balance_sheet(frequence="a", trailing=True, count=5)

**Describe alternatives you've considered**
Ticker.balance_sheet(frequence="a", trailing=True, as_of=Date)

**Additional context**
Not sure if this is easy to do from the API, but I found the capability to retrieve further historical data quite useful for research

**Comment by dpguthrie** [comment]
This functionality exists if you have a Yahoo Finance premium account.  Otherwise, the API limits to either the 4 most recent quarters or years.  If you do have a premium account though, you can access more data with the following:

```
Ticker('aapl').p_all_financial_data()
```

**Comment by zhenyulin** [comment]
thanks for clarifying that!
