### ISSUE TITLE
currency_converter rate_limit docs

### ISSUE THREAD

**Issue by zhenyulin** [dpguthrie/yahooquery#52]
**Is your feature request related to a problem? Please describe.**
It is easy to get 429 Error when using currency_converter to fetch exchange rates for a list of currencies. 

`RetryError: HTTPSConnectionPool(host='adsynth-ofx-quotewidget-prod.herokuapp.com', port=443): Max retries exceeded with url: /api/1 (Caused by ResponseError('too many 429 error responses',))`

It looks that it is using an API from sources other than Yahoo Finance, and the rate limit rules are not very clear. And it can actually be in effect for quite long, like a day, which is blocking things once an error is made.

**Describe the solution you'd like**
docs of rate limit

**Comment by dpguthrie** [comment]
I'll have to do a little more research on this one.  The URL this data comes from is outside of Yahoo Finance, as you noted above, and the third party must be limiting the requests.

**Comment by dpguthrie** [comment]
Don't know exact details of rate limiting, but there's now a warning in the docs.

![image](https://user-images.githubusercontent.com/10198967/196006668-c446dbcc-d848-4703-8589-e46fbf1999b0.png)
