### ISSUE TITLE
docs: stock split

### ISSUE THREAD

**Issue by zhenyulin** [dpguthrie/yahooquery#54]
**Is your feature request related to a problem? Please describe.**
I guess this more of a question about the data from Yahoo Finance API. I'm trying to get the MarketCap history of any stock, for which I need to factor in stock split. Upon checking the "ShareIssued" of APPL, it looks like the stock split happened in Aug, 2020 is not reflected on their balance sheet.

From some research, it looks to me that the all price history adjusted for any stock split in Yahoo Finance (https://money.stackexchange.com/questions/44142/how-does-yahoo-finance-adjust-stock-data-for-splits-and-dividends), not sure if this is also true for Issued Share?

**Describe the solution you'd like**
some clarification at the docs regarding share split;

**Comment by dpguthrie** [comment]
Not sure of the answer here, but more than happy to accept a PR to the docs if you have something.
