### ISSUE TITLE
progress bar not correct when pulling a long list of data

### ISSUE THREAD

**Issue by zhenyulin** [dpguthrie/yahooquery#57]
**Describe the bug**
When pulling a long list of data, say over 500 tickers, the progress bar finishes marginally earlier than when the result is actually ready.

**To Reproduce**
get_financial_data(tickers, progress=True, asynchronous=True)

**Expected behavior**
when the progress bar reaches 100%, almost instantly the results are returned

**Additional context**

**Comment by dpguthrie** [comment]
The progress bar is utilized in making the requests, not in combining all the data frames once the requests are complete. If you have a better solution, please feel free to open a pull request.
