### ISSUE TITLE
Inconsistent data

### ISSUE THREAD

**Issue by alexlopespereira** [dpguthrie/yahooquery#58]
**Describe the bug**
The close price from yesterday (2020-12-28) of NFLX34 seems not to be correct. But in fact, it was 52.50 but the api is returning 54.79.

**To Reproduce**
s = Ticker('NFLX34.SA')
df2 = s.history(period='2d', interval="1d")

 - I'm using yahooquery version 2.2.11

And I downloaded the original data from bvmf.bmfbovespa.com.br/InstDados/SerHist/COTAHIST_D28122020.ZIP

Have I done anything wrong?

**Comment by dpguthrie** [comment]
Here's what I'm seeing on YF:

![image](https://user-images.githubusercontent.com/10198967/103293713-9ef5a280-49ad-11eb-9fc9-911b218d7a5f.png)

The 54.79 closing price seen on YF matches what I'm getting from the library.

**Comment by alexlopespereira** [comment]
Thanks for your quick answer. The difference might be on YF database. Am I missing anything?

Take a look at a screenshot of my broker's dashboard today. There, the column name "Fech." means closing price.

![image](https://user-images.githubusercontent.com/6627726/103295680-3f11f280-49d3-11eb-8f77-160bbaada4d6.png)

Now, take a look at the closing price of investing.com, uol.com.br and infomoney.com.br. They are all 52.50.

![image](https://user-images.githubusercontent.com/6627726/103296170-4ab1e900-49d4-11eb-8a36-4e71187a8392.png)
![image](https://user-images.githubusercontent.com/6627726/103296737-800b0680-49d5-11eb-93d5-89fc6bd97e29.png)
![image](https://user-images.githubusercontent.com/6627726/103296815-ac268780-49d5-11eb-8597-a05417074613.png)

**Comment by dpguthrie** [comment]
That's interesting.  I'll have to do a little more digging, but the problem appears to be on YF's side, as I'm just pulling in the data they're showing.  If you find something, please let me know also.

**Comment by maxBeinlich** [comment]
This issue seems to be with Yahoo! Finance itself and less with the API / library. The inconsistency has since been updated and should now return the correct value (haven't tested it out). However Yahoo! Finance now displays the correct value.

<img width="907" alt="Screenshot 2021-03-26 at 22 25 49" src="https://user-images.githubusercontent.com/46826147/112694412-97497b00-8e82-11eb-8936-201d8a882576.png">

This issue should be resolved.
