### ISSUE TITLE
premium data rate limit

### ISSUE THREAD

**Issue by zhenyulin** [dpguthrie/yahooquery#59]
**Describe the bug**
I'm getting the MaxRetries error when using `p_get_financial_data` after around fetching 300 tickers continuously

> HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /ws/fundamentals-timeseries/v1/finance/premium/timeseries/ATUS?type=annualTotalAssets%2CannualTotalDebt%2CannualGoodwillAndOtherIntangibleAssets%2CannualEndCashPosition%2CannualFreeCashFlow%2CannualTotalRevenue%2CannualTotalExpenses%2CannualNormalizedEBITDA%2CannualGrossProfit%2CannualShareIssued%2CtrailingTotalAssets%2CtrailingTotalDebt%2CtrailingGoodwillAndOtherIntangibleAssets%2CtrailingEndCashPosition%2CtrailingFreeCashFlow%2CtrailingTotalRevenue%2CtrailingTotalExpenses%2CtrailingNormalizedEBITDA%2CtrailingGrossProfit%2CtrailingShareIssued&period1=493590046&period2=1610048367&merge=false&padTimeSeries=false&lang=en-US&region=US&corsDomain=finance.yahoo.com (Caused by ResponseError('too many 404 error responses',))

```python
def pull_financial_history(
    tickers,
    fields=FINANCIAL_HISTORY_FIELDS,
    progress=False,
    use_premium=False,
):
    stocks = Ticker(
        tickers,
        progress=progress,
        asynchronous=True,
        max_workers=12,
        status_forcelist=[404, 429, 500, 502, 503, 504],
        backoff_factor=1,
        username=username if use_premium else None,
        password=password if use_premium else None,
    )

    method = "p_get_financial_data" if use_premium else "get_financial_data"

    return getattr(stocks, method)(
        FINANCIAL_HISTORY_FIELDS,
        frequency="a",
        trailing=True,
    )
```

**Expected behavior**
I'm expecting no rate limit when using the premium, or is there something I missed here?

**Additional context**
I'm currently still on Free Trial of Yahoo Finance Premium

**Comment by dpguthrie** [comment]
Because this is an unofficial API, and the amount of data you're requesting at once is so high, I would absolutely expect YF to block your requests.  And, unfortunately, they don't provide a response that would indicate that - they'll just continue to show the user 404 errors.  Have you tried using proxies while making requests like this?

**Comment by zhenyulin** [comment]
Hi @dpguthrie, thanks for the update.

I've tried with proxies from free-proxy but it doesn't seem to help. 

Furthermore, I've noticed that the rate limit on non-premium financial data has been dramatically reduced as well. Previously had no issue pulling data for 3000+ tickers, while now probably got stuck around 1000. Is there something I missed or something has changed?

**Comment by dpguthrie** [comment]
I think YF has become more proactive in blocking requests like these.  And, it also seems to come and go based on what I'm seeing from some other users.  Also, my understanding of free-proxy is that so many users could be using the same address and they can get blacklisted rather easily.  I used to use something called Crawlera (now apparently called [zyte](https://www.zyte.com/smart-proxy-manager/) that uses a rotating proxy.  It's a paid service, but I never had issues with getting blocked.  

Perhaps the configuration of the request could be looked at though.  I could employ a similar approach when instantiating a premium Ticker instance - use selenium to retrieve the relevant cookies to make the request seem more legitimate, among other things.  But then time increases when creating a `Ticker` instance.

**Comment by zhenyulin** [comment]
@dpguthrie I assume the rate limit is set against IP address over a period of time? Not sure if there's anything else being factored in especially when using `p_get_financial_data`?

Today I had an initial run stuck at around 160. I have tried using a different network with a different IP, but still got stuck. Have also tried the proxy, the URL tested successfully on the zyte website, but get the MaxRetriesError when using my code running in a kernel. Kind of strange.

**Comment by dpguthrie** [comment]
Not sure why I didn't think of this earlier - you had to login in order to utilize that method.  So, every request you make (after logging in) has something that identifies you with the request so you can retrieve that data.  From there, it's probably pretty easy for them to block your requests.

**Comment by zhenyulin** [comment]
@dpguthrie very true, I just thought about this and about to post. I'll try a different account to see how it goes.

**Comment by zhenyulin** [comment]
The best way to deal with this here is probably to break down requests in batches and execute them in time intervals here.
