### ISSUE TITLE
{'error': 'HTTP 404 Not Found.  Please try again'} when requesting large batches of data

### ISSUE THREAD

**Issue by keskinmbaha** [dpguthrie/yahooquery#61]
As the title states, when I request data on large batches of symbols, I receive "{'error': 'HTTP 404 Not Found.  Please try again'}". If I request the data one by one it used to not give any error, but lately after some amount of requests, it starts giving me this error. The number of requests it takes to start receiving the error is different each time. Once it was after 700 requests, another was sometime after 1000, etc. If I try to request all the symbols (3000+) at once it only gives the error and no partial data. After receiving the error, it doesn't give any data on request until some amount of time has passed.

The way to possibly reproduce is to request data (I tried to request balance sheet data) for at least 1000 symbols within a short time frame (I am not sure how long or how many since it differs with each request). If you do the request all at once it should give the error without any data. But, if you make the requests individually, after some X amount of requests it starts giving the error and no data.

I expected to receive the balance sheet data as I had not issue of this before.

MacOs Big Sur
Safari
yahooquery version 2.2.12
python 3.9+

If this is a number of requests exceeded error, I think it would be helpful to have it in the documentation and give a different error like "Too many requests" instead of the http not found error (although if there is already some documentation on it, I would appreciate a pointer to where it is).

**Comment by dpguthrie** [comment]
This is most definitely an example of YF actively blocking your requests.  The problem, however, is YF doesn't tell the user that - they'll continue to show 404 errors as if the data / page doesn't exist.  You can try several things:

- Include 404 in the [`status_forcelist`](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#status_forcelist) keyword argument when you initialize your Ticker instance - .  This will force a retry when you get a 404 response.  Make sure all your symbols are [valid](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#validate) though if you're going to do this.
- Increase the `backoff_factor` and/or the number of times to `retry` if you get a `MaxRetryError`
- Use a [proxy](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#proxies) - this is probably your best bet.

**Comment by keskinmbaha** [comment]
I see. I'll try some of the tips you gave then. Thanks!

**Comment by DevHeron** [comment]
When I add 404 to my status_forcelist, it returns 'too many 404 '. But if I use validation it returns 'expected str came NAType instead', even thouh according to my tickers info they are all strings... What can I do?
