### ISSUE TITLE
history function loses splits if dividends exist

### ISSUE THREAD

**Issue by kpad-git** [dpguthrie/yahooquery#66]
**Describe the bug**
Pretty straightforward to reproduce. When the history function is asked for prices in a certain range, having dividends zeroes out splits that are otherwise there.

**To Reproduce**
import yahooquery as yq
aapl=yq.Ticker('AAPL')
aapl.history(start="2020-08-08",end="2020-09-06",interval="1d")
aapl.history(start="2020-08-07",end="2020-09-06",interval="1d")

**Expected behavior**
In the first history call above (that excludes the dividend on Aug 7, 2020), the row for Aug 31 shows splits=4.0 (correct)
In the second history call (including Aug 7), the row for Aug 31 shows splits=0.0 (wrong).

I tried a bunch of date ranges, and the one that added the dividend column (Aug 7) made the splits for Aug 31 change.

**Comment by dpguthrie** [comment]
Thanks for catching that.  I see what's going on and can get a fix pretty quickly.

**Comment by dpguthrie** [comment]
Should be good in 2.2.13:

```
import pandas as pd
import yahooquery as yq

aapl = yq.Ticker('AAPL')
df1 = aapl.history(start='2020-08-07', end='2020-09-06')
df2 = aapl.history(start='2020-08-08', end='2020-09-06')

pd.testing.assert_series_equal(df1[1:]['splits'], df2['splits'])
```

**Comment by kpad-git** [comment]
Nice, thanks for the quick fix!
