### ISSUE TITLE
Question - is there a way to get the currency used for a given financial statement?

### ISSUE THREAD

**Issue by kpad-git** [dpguthrie/yahooquery#67]
I didn't know how else to submit this - if it doesn't exist, I can convert it to a "feature request".

This comes up mostly for ADR securities in the US. For example, LXFR is foreign, but reports in USD, while ASML is also foreign and reports in EUR. Both trade in USD, so I can't look at the currency of the security itself.

The Yahoo finance pages show this when you look at the financial statements (they show USD for the price, and EUR for the financial reports for ASML). Is there some way to find the financial statement currency?

**Comment by dpguthrie** [comment]
Check out the newest version - 2.2.14.  All of the financials data frames (cash_flow, income_statement, balance_sheet, all_financial_data, get_financial_data) will now include an additional column "currencyCode".

```
from yahooquery import Ticker

t = Ticker('ASML')
t.get_financial_data('NetIncome')

         asOfDate periodType currencyCode     NetIncome
symbol                                                 
ASML   2017-12-31        12M          EUR  2.135200e+09
ASML   2018-12-31        12M          EUR  2.585400e+09
ASML   2019-12-31        12M          EUR  2.574100e+09
ASML   2020-12-31        12M          EUR  3.553700e+09
ASML   2020-12-31        TTM          EUR  3.553700e+09
```

**Comment by kpad-git** [comment]
Awesome, thanks!
