### ISSUE TITLE
Get more than 4 years of financial statements?

### ISSUE THREAD

**Issue by nicksteele1702** [dpguthrie/yahooquery#68]
Is it possible to pull more than 4 years of income statement/cash flow/balance sheet with premium?  If not, how could I modify the source code to do so? Thank you!

**Comment by dpguthrie** [comment]
Yeah - have you tried and are unable to?  You can see in the [documentation](https://yahooquery.dpguthrie.com/guide/ticker/premium/#p_balance_sheet) where I retrieved data for `AAPL` back to 1985.
