### ISSUE TITLE
Catch {'error': 'HTTP 404 Not Found.  Please try again'} for invalid ticker symbol

### ISSUE THREAD

**Issue by akfuster** [dpguthrie/yahooquery#69]
Would it be possible to catch the case where a call to all_financial_data fails because one of the tickers is not on yahoo finance? I am gathering data from a large list of symbols, some of which give me this 404 error.

Thanks

**Comment by dpguthrie** [comment]
Have you tried the `validate` keyword argument to remove invalid symbols?  https://yahooquery.dpguthrie.com/guide/keyword_arguments/#validate

**Comment by dpguthrie** [comment]
See here for additional strategies:  https://github.com/dpguthrie/yahooquery/issues/75#issuecomment-798903386
