### ISSUE TITLE
EBIT calculation

### ISSUE THREAD

**Issue by mchandlernz** [dpguthrie/yahooquery#7]
Hello,

I was wondering what your method for calculating EBIT was?

It seems in some (most) cases EBIT is not posted on yahoo's income statements and there is some calculation to get there.

**Comment by dpguthrie** [comment]
I'm not calculating anything.  The EBIT data you see is what's coming straight from Yahoo Finance.  But, it looks like the calculation they're using is:

Earnings Before Taxes + Net Interest Expense + Non Operating Expenses + Unusual Expenses

I've only checked a couple different symbols (AAPL, MSFT) and the EBIT returned through the income_statement method matches what I've seen on other sites with similar calculations.
