### ISSUE TITLE
Ticker bulk download status bar

### ISSUE THREAD

**Issue by BrononymousEngineer** [dpguthrie/yahooquery#71]
Hi, I was wondering if an option could be added to the Ticker class which displays a status bar showing the download progress when calling yahooquery.Ticker(x). some_module, where x is a list or string of multiple symbols. 

In my own application I have achieved this by iterating through a list of symbols, and getting data for each one individually, like:

```
symbols = a list of symbol strings
data = {}
i = 1
max_i = len(symbols)
for s in symbols:
    data[s] = yahooquery.Ticker(s).some_module[s]
    print(f'Downloading...{round(100*(i/max_i), 2)}%', end='\r')
    i += 1
```
But this is much slower than simply calling Ticker on the entire list of symbols. For a small-ish list of symbols it's not a big deal, but I'm working on a custom screener where I may have a few thousand symbols to download data for, in which case it's very useful to see the download progress.

I apologize if this is already available and I missed it.

**Comment by dpguthrie** [comment]
Have you checked out the documentation?  https://yahooquery.dpguthrie.com/guide/keyword_arguments/#progress

**Comment by BrononymousEngineer** [comment]
I checked the docstring of the Ticker class definition...my apologies

**Comment by dpguthrie** [comment]
No worries at all. I should probably update the docstring if it’s not there.
