### ISSUE TITLE
HTTP 404 Not Found 

### ISSUE THREAD

**Issue by Pollinetor** [dpguthrie/yahooquery#75]
Hi, when i try to download stock financials data in loop for each stock in ptf (500 stocks) sometimes i get this error:
"HTTP 404 Not Found Please  Try Again" . 
Sometimes the code stops after 300th stock, sometimes it breaks at the beginning. 
It's an API problem ? 

Thanks 

Paolo

**Comment by Pollinetor** [comment]
I used the option validate=True and stocks in list are always the same .

**Comment by dpguthrie** [comment]
This is most likely Yahoo Finance blocking your requests.  You can try different strategies to get around that though:

- Use the [status_forcelist](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#status_forcelist) keyword argument and add 404.  This will ensure a retry when a 404 error is returned (which Yahoo Finance returns when they're blocking requests).
- Increase the [backoff_factor](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#backoff_factor) which will increase the time taken between retries.
- Increase the number of [retries](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#retry)
- The best way though is to use a [proxy](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#proxies) argument.

**Comment by Pollinetor** [comment]
Thanks

now i'm using this:

for stock in tickers:
    # select information ! optimize run time remove loop on requests
    ticker = yahooquery.Ticker(stock, validate=True, status_forcelist=[404], backoff_factor=5, retry=10, progress=True)

And after several minutes i get datas. 
Iit is wiser to download the entire stock list directly, I guess.
