### ISSUE TITLE
earning_history not working for region india

### ISSUE THREAD

**Issue by Valeeswaran** [dpguthrie/yahooquery#76]
I am using the following code:
import yahooquery as yq
qstock = yq.Ticker("tatasteel.ns", country='india')
print(qstock.earning_history)

And getting the following error message. Please help me to resolve the issue.
{'tatasteel.ns': 'No fundamentals data found for any of the summaryTypes=earningsHistory'}

**Comment by dpguthrie** [comment]
This is the message returned from the API when no data is available for a specific module.  You can always double-check Yahoo Finance to see if the data is actually missing, which in this case it is - https://in.finance.yahoo.com/quote/TATASTEEL.NS/analysis?p=TATASTEEL.NS
