### ISSUE TITLE
Guidance for using the proxies keyword

### ISSUE THREAD

**Issue by kpad-git** [dpguthrie/yahooquery#81]
I've been trying to use the proxies keyword, and wanted some guidance to make sure I am doing it correctly. I didn't see any previous issues that detailed this so I thought it might be helpful for others too.

I am using code like this with proxy servers found online:

`proxy={'http':'http://555.55.55.555:3128', 'https':'http://555.55.55.555:3128'}
Ticker("AAPL",proxies=proxy,verify=False).balance_sheet()`

One thing I noticed is that I have to use "http" even in the "https" dictionary entry. If I don't turn off verify, I always get "ConnectTimeoutError". If I do turn off verify, it works with a warning ("Adding certificate verification is strongly advised.").

Is this the best way to be doing this? Or is there a better way?

**Comment by kpad-git** [comment]
With further tinkering, I have found a few things that might help anybody else doing this:

1) Stopping the warnings can be done by using "logging" - see https://stackoverflow.com/questions/11029717/how-do-i-disable-log-messages-from-the-requests-library

2) I ended up running without verify=False, which seemed to work if the proxy is working.

**Comment by dpguthrie** [comment]
Sounds like you were able to get this figured out so closing it out.
