### ISSUE TITLE
Not all screeners from Screener().available_screeners is accessible

### ISSUE THREAD

**Issue by mrtuborg** [dpguthrie/yahooquery#85]
**Describe the bug**
The method Screener().available_screeners returns a list of 325 screeners, but only 79 is accessible indeed.

**To Reproduce**

I wrote a sample script:
```
from yahooquery import Screener
s = Screener()
api_screeners = s.available_screeners

for value in api_screeners:
  selected = s.get_screeners(value, 1)
  try:
    name = selected[value]['canonicalName']
  except (KeyError, TypeError) as err:
    print(value + ': is unavailable')
    pass
  else:
    print(value + ': ' + name)
```
1. Start script and count all lines:
`python3 screeners.py | wc -l`
The result is:
`325`
2. Start script and count lines for available screeners:
`python3 screeners.py | grep -v 'unavailable' | wc -l`
The result is:
`79`

**Expected behavior**
`python3 screeners.py | grep -v 'unavailable' | wc -l` should return 325

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Python 3.9.4
 - yahooquery 2.2.5

**Additional context**

As a programmer, I would like to spend some time to help to fix this issue but have no idea where to start.
Any suggestions?

**Comment by dpguthrie** [comment]
See #116
