### ISSUE TITLE
Is history data delayed? 

### ISSUE THREAD

**Issue by liyuling** [dpguthrie/yahooquery#86]
I found that at the market open, I could successfully request history data for today, however, the open price is SAME as yesterday's open price. Not sure why Yahoo did that or there is a delay for Yahoo to update the open price for today in historical data?

**Comment by dpguthrie** [comment]
The data is returned to the user exactly as it's given from the API.  Not sure how YF is handling this internally.  Closing cause I don't think there's anything I can on my end.
