### ISSUE TITLE
Earnings date resulting in a range instead of a single date

### ISSUE THREAD

**Issue by rdaher** [dpguthrie/yahooquery#89]
If we run ticker.earnings for a particular stock, we get  a range of dates for the upcoming earnings date. The same applies whether we use ticker.calendar_events
<img width="573" alt="screenshot_39" src="https://user-images.githubusercontent.com/59781123/126067286-ea95bdf2-ad86-4770-9bad-f18e4f81f752.png">

However, if we look at the yahoo earnings calendar website for the same ticker (https://finance.yahoo.com/calendar/earnings/?symbol=myo), we get a specific date and time as noted below:
<img width="937" alt="screenshot_40" src="https://user-images.githubusercontent.com/59781123/126067387-fa801020-21d6-48dd-ab56-4527dfedd5bc.png">

Any chance we could get the exact date pulled using yahooquery?
Thank you much Doug!!

**Comment by dpguthrie** [comment]
This is the data that is returned from the API.  Not sure how I would be able to validate.  Closing as not planned.
