### ISSUE TITLE
Q4 net income incorrect

### ISSUE THREAD

**Issue by gabjew90** [dpguthrie/yahooquery#9]
![image](https://user-images.githubusercontent.com/64626637/80782621-c7ca4d00-8b2b-11ea-9f2f-615f2f7e51a4.png)

**Comment by dpguthrie** [comment]
Thanks for letting me know.  It looks like the last quarter is being combined with the TTM.  I'll have a fix released shortly.

**Comment by dpguthrie** [comment]
@gabjew90 I just released 2.2.2 with the fix.

**Comment by gabjew90** [comment]
Hi Doug,

Thanks for the reply and quick fix! love the package so far. Do you think
you can show more than 4 quarters worth of earnings data?

Gabriel

**Comment by dpguthrie** [comment]
Do you see that anywhere on Yahoo Finance?  I haven't seen it on their site so I'm not sure they provide that info.
