### ISSUE TITLE
execution just hangs in aws lambda python environment

### ISSUE THREAD

**Issue by shortvol** [dpguthrie/yahooquery#91]
**Describe the bug**
I am pulling intraday data for ~500 tickers using asynchronous = True and it works on my local machine. However, I tried setting up aws lambda function with python 3.7 environment and after 15mins run time the process gets killed for hitting time limit without any output

**Additional context**
I ran it with logging set to debug mode just to see what could be the issue. Screenshot attached. There seem to be multiple "resetting dropped connection" messages. All installed packages are compatible with the amazon linux image, so that doesn't seem to be the issue. Does anyone have any idea what is going on here? Appreciate any help, thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/47490792/127237770-487ce85c-aba1-4351-b852-424a10ef67d4.png)

**Comment by dpguthrie** [comment]
I've never run this in a lambda so am unsure of how to troubleshoot here.  I would recommend something on StackOverflow for folks with more lambda experience.  If you do find something, happy to take a look at what may be going on, but am going to close out for now as I am unable to fix.
