### ISSUE TITLE
Error while fetcthing price <yahooquery.ticker.Ticker object at 0x000001E1AEDEA888>

### ISSUE THREAD

**Issue by raviyellani** [dpguthrie/yahooquery#92]
2 days back it worked fine but today when tried to run the code error <yahooquery.ticker.Ticker object at 0x000001E1AEDEA888>
is displaying also some time the previous day price is received while using .price api
![yahooqueryerror](https://user-images.githubusercontent.com/4957036/129674972-498404c6-e53e-4ec2-b293-fedfd45c137d.png)

**Comment by dpguthrie** [comment]
Closing as nothing is given to reproduce.
